# Code generated by pluginart. DO NOT EDIT.
from pluginart import serve
from contract import CONTRACT_HASH
from handler import handle

if __name__ == '__main__':
    serve(handle, contract_hash=CONTRACT_HASH)
