// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package echo

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CallRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCallRequest(buf []byte, offset flatbuffers.UOffsetT) *CallRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CallRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishCallRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCallRequest(buf []byte, offset flatbuffers.UOffsetT) *CallRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CallRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCallRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CallRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CallRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CallRequest) RequestId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CallRequest) MutateRequestId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *CallRequest) DeadlineUnixMs() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CallRequest) MutateDeadlineUnixMs(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func (rcv *CallRequest) TraceId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CallRequest) SpanId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CallRequest) PayloadType() RequestPayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return RequestPayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CallRequest) MutatePayloadType(n RequestPayload) bool {
	return rcv._tab.MutateByteSlot(12, byte(n))
}

func (rcv *CallRequest) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func CallRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func CallRequestAddRequestId(builder *flatbuffers.Builder, requestId uint64) {
	builder.PrependUint64Slot(0, requestId, 0)
}
func CallRequestAddDeadlineUnixMs(builder *flatbuffers.Builder, deadlineUnixMs int64) {
	builder.PrependInt64Slot(1, deadlineUnixMs, 0)
}
func CallRequestAddTraceId(builder *flatbuffers.Builder, traceId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(traceId), 0)
}
func CallRequestAddSpanId(builder *flatbuffers.Builder, spanId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(spanId), 0)
}
func CallRequestAddPayloadType(builder *flatbuffers.Builder, payloadType RequestPayload) {
	builder.PrependByteSlot(4, byte(payloadType), 0)
}
func CallRequestAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(payload), 0)
}
func CallRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
