// Code generated by pluginart. DO NOT EDIT.
package echo

// ContractHash is the SHA-256 of the schema file used to generate this code.
// The pluginart runtime verifies this matches on every connection.
const ContractHash = "sha256:094f99745014e0e307ad2b73394a45887059d3ce7fcda59fbd741f77e7904a14"
