// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package echo

import "strconv"

type RequestPayload byte

const (
	RequestPayloadNONE        RequestPayload = 0
	RequestPayloadEchoRequest RequestPayload = 1
)

var EnumNamesRequestPayload = map[RequestPayload]string{
	RequestPayloadNONE:        "NONE",
	RequestPayloadEchoRequest: "EchoRequest",
}

var EnumValuesRequestPayload = map[string]RequestPayload{
	"NONE":        RequestPayloadNONE,
	"EchoRequest": RequestPayloadEchoRequest,
}

func (v RequestPayload) String() string {
	if s, ok := EnumNamesRequestPayload[v]; ok {
		return s
	}
	return "RequestPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
