// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package echo

import "strconv"

type ResponsePayload byte

const (
	ResponsePayloadNONE         ResponsePayload = 0
	ResponsePayloadEchoResponse ResponsePayload = 1
)

var EnumNamesResponsePayload = map[ResponsePayload]string{
	ResponsePayloadNONE:         "NONE",
	ResponsePayloadEchoResponse: "EchoResponse",
}

var EnumValuesResponsePayload = map[string]ResponsePayload{
	"NONE":         ResponsePayloadNONE,
	"EchoResponse": ResponsePayloadEchoResponse,
}

func (v ResponsePayload) String() string {
	if s, ok := EnumNamesResponsePayload[v]; ok {
		return s
	}
	return "ResponsePayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
