# Code generated by pluginart. DO NOT EDIT.
from pluginart import PluginManager

try:
    from .pluginart_helpers import BuildEchoCallRequest, DecodeEchoResponse
except ImportError:
    from pluginart_helpers import BuildEchoCallRequest, DecodeEchoResponse


class echoClient:
    """Typed host-side client for the echo plugin."""

    def __init__(self, manager: PluginManager, plugin_name: str) -> None:
        self._manager = manager
        self._plugin_name = plugin_name

    def Echo(self, builder, payload: int):
        """Call Echo on the plugin. payload is a EchoRequest table offset."""
        raw = self._manager.call(self._plugin_name, BuildEchoCallRequest(builder, payload))
        response, _ = DecodeEchoResponse(raw)
        return response
