# Code generated by pluginart. DO NOT EDIT.
from dataclasses import dataclass

try:
    from .echo import CallRequest, CallResponse, EchoRequest, EchoResponse, RequestPayload, ResponsePayload
except ImportError:
    from echo import CallRequest, CallResponse, EchoRequest, EchoResponse, RequestPayload, ResponsePayload


@dataclass(frozen=True)
class CallContext:
    request_id: int


def BuildEchoCallRequest(builder, payload: int) -> bytes:
    """Wrap a EchoRequest table offset in a CallRequest envelope."""
    CallRequest.CallRequestStart(builder)
    CallRequest.CallRequestAddPayloadType(builder, RequestPayload.RequestPayload.EchoRequest)
    CallRequest.CallRequestAddPayload(builder, payload)
    request = CallRequest.CallRequestEnd(builder)
    builder.Finish(request)
    return bytes(builder.Output())


def DecodeEchoRequest(payload: bytes) -> tuple[EchoRequest.EchoRequest, CallContext]:
    """Unwrap a CallRequest envelope and return the EchoRequest payload."""
    request = CallRequest.CallRequest.GetRootAs(bytearray(payload), 0)
    got = request.PayloadType()
    want = RequestPayload.RequestPayload.EchoRequest
    if got != want:
        raise ValueError(f"expected EchoRequest payload, got {got}")
    union_obj = request.Payload()
    if union_obj is None:
        raise ValueError("missing EchoRequest payload")
    out = EchoRequest.EchoRequest()
    out.Init(union_obj.Bytes, union_obj.Pos)
    return out, CallContext(request_id=request.RequestId())


def BuildEchoCallResponse(call: CallContext, builder, payload: int) -> bytes:
    """Wrap a EchoResponse table offset in a CallResponse envelope."""
    CallResponse.CallResponseStart(builder)
    CallResponse.CallResponseAddRequestId(builder, call.request_id)
    CallResponse.CallResponseAddPayloadType(builder, ResponsePayload.ResponsePayload.EchoResponse)
    CallResponse.CallResponseAddPayload(builder, payload)
    response = CallResponse.CallResponseEnd(builder)
    builder.Finish(response)
    return bytes(builder.Output())


def DecodeEchoResponse(payload: bytes) -> tuple[EchoResponse.EchoResponse, CallContext]:
    """Unwrap a CallResponse envelope and return the EchoResponse payload."""
    response = CallResponse.CallResponse.GetRootAs(bytearray(payload), 0)
    got = response.PayloadType()
    want = ResponsePayload.ResponsePayload.EchoResponse
    if got != want:
        raise ValueError(f"expected EchoResponse payload, got {got}")
    union_obj = response.Payload()
    if union_obj is None:
        raise ValueError("missing EchoResponse payload")
    out = EchoResponse.EchoResponse()
    out.Init(union_obj.Bytes, union_obj.Pos)
    return out, CallContext(request_id=response.RequestId())


