// Code generated by pluginart. DO NOT EDIT.
package repeat

import (
	"fmt"

	flatbuffers "github.com/google/flatbuffers/go"
)

// CallContext carries RPC envelope metadata between generated decode/build helpers.
type CallContext struct {
	RequestID uint64
}

// DecodeRepeatRequest unwraps a CallRequest envelope and returns the RepeatRequest payload.
func DecodeRepeatRequest(payload []byte) (*RepeatRequest, CallContext, error) {
	req := GetRootAsCallRequest(payload, 0)
	if got := req.PayloadType(); got != RequestPayloadRepeatRequest {
		return nil, CallContext{}, fmt.Errorf("expected RepeatRequest payload, got %s", got.String())
	}
	var tab flatbuffers.Table
	if !req.Payload(&tab) {
		return nil, CallContext{}, fmt.Errorf("missing RepeatRequest payload")
	}
	out := &RepeatRequest{}
	out.Init(tab.Bytes, tab.Pos)
	return out, CallContext{RequestID: req.RequestId()}, nil
}

// BuildRepeatCallResponse wraps a RepeatResponse table offset in a CallResponse envelope.
func BuildRepeatCallResponse(call CallContext, builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) []byte {
	CallResponseStart(builder)
	CallResponseAddRequestId(builder, call.RequestID)
	CallResponseAddPayloadType(builder, ResponsePayloadRepeatResponse)
	CallResponseAddPayload(builder, payload)
	resp := CallResponseEnd(builder)
	builder.Finish(resp)
	return builder.FinishedBytes()
}
