// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package repeat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RepeatResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsRepeatResponse(buf []byte, offset flatbuffers.UOffsetT) *RepeatResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RepeatResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishRepeatResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRepeatResponse(buf []byte, offset flatbuffers.UOffsetT) *RepeatResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RepeatResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRepeatResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RepeatResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RepeatResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RepeatResponse) Output() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RepeatResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func RepeatResponseAddOutput(builder *flatbuffers.Builder, output flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(output), 0)
}
func RepeatResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
