// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package repeat

import "strconv"

type ResponsePayload byte

const (
	ResponsePayloadNONE           ResponsePayload = 0
	ResponsePayloadRepeatResponse ResponsePayload = 1
)

var EnumNamesResponsePayload = map[ResponsePayload]string{
	ResponsePayloadNONE:           "NONE",
	ResponsePayloadRepeatResponse: "RepeatResponse",
}

var EnumValuesResponsePayload = map[string]ResponsePayload{
	"NONE":           ResponsePayloadNONE,
	"RepeatResponse": ResponsePayloadRepeatResponse,
}

func (v ResponsePayload) String() string {
	if s, ok := EnumNamesResponsePayload[v]; ok {
		return s
	}
	return "ResponsePayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
