// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class RepeatResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RepeatResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRepeatResponse(bb:flatbuffers.ByteBuffer, obj?:RepeatResponse):RepeatResponse {
  return (obj || new RepeatResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRepeatResponse(bb:flatbuffers.ByteBuffer, obj?:RepeatResponse):RepeatResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RepeatResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

output():string|null
output(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
output(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startRepeatResponse(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addOutput(builder:flatbuffers.Builder, outputOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, outputOffset, 0);
}

static endRepeatResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRepeatResponse(builder:flatbuffers.Builder, outputOffset:flatbuffers.Offset):flatbuffers.Offset {
  RepeatResponse.startRepeatResponse(builder);
  RepeatResponse.addOutput(builder, outputOffset);
  return RepeatResponse.endRepeatResponse(builder);
}
}
