# Code generated by pluginart. DO NOT EDIT.
from dataclasses import dataclass

from fb.repeat import CallRequest, CallResponse, RepeatRequest, RepeatResponse, RequestPayload, ResponsePayload


@dataclass(frozen=True)
class CallContext:
    request_id: int


def DecodeRepeatRequest(payload: bytes) -> tuple[RepeatRequest.RepeatRequest, CallContext]:
    """Unwrap a CallRequest envelope and return the RepeatRequest payload."""
    request = CallRequest.CallRequest.GetRootAs(bytearray(payload), 0)
    got = request.PayloadType()
    want = RequestPayload.RequestPayload.RepeatRequest
    if got != want:
        raise ValueError(f"expected RepeatRequest payload, got {got}")
    union_obj = request.Payload()
    if union_obj is None:
        raise ValueError("missing RepeatRequest payload")
    out = RepeatRequest.RepeatRequest()
    out.Init(union_obj.Bytes, union_obj.Pos)
    return out, CallContext(request_id=request.RequestId())


def BuildRepeatCallResponse(call: CallContext, builder, payload: int) -> bytes:
    """Wrap a RepeatResponse table offset in a CallResponse envelope."""
    CallResponse.CallResponseStart(builder)
    CallResponse.CallResponseAddRequestId(builder, call.request_id)
    CallResponse.CallResponseAddPayloadType(builder, ResponsePayload.ResponsePayload.RepeatResponse)
    CallResponse.CallResponseAddPayload(builder, payload)
    response = CallResponse.CallResponseEnd(builder)
    builder.Finish(response)
    return bytes(builder.Output())


