// Code generated by pluginart. DO NOT EDIT.
package repeat

// ContractHash is the SHA-256 of the schema file used to generate this code.
// The pluginart runtime verifies this matches on every connection.
const ContractHash = "sha256:f83b4e6033244f2dbdcba6d61e07a7eed3e0a3cc49eb41ebdb57165231adaf8d"
