// Code generated by pluginart. DO NOT EDIT.
package repeat

import (
	"fmt"

	flatbuffers "github.com/google/flatbuffers/go"
)

// CallContext carries RPC envelope metadata between generated decode/build helpers.
type CallContext struct {
	RequestID uint64
}

// BuildRepeatCallRequest wraps a RepeatRequest table offset in a CallRequest envelope.
func BuildRepeatCallRequest(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) []byte {
	CallRequestStart(builder)
	CallRequestAddPayloadType(builder, RequestPayloadRepeatRequest)
	CallRequestAddPayload(builder, payload)
	req := CallRequestEnd(builder)
	builder.Finish(req)
	return builder.FinishedBytes()
}

// DecodeRepeatRequest unwraps a CallRequest envelope and returns the RepeatRequest payload.
func DecodeRepeatRequest(payload []byte) (*RepeatRequest, CallContext, error) {
	req := GetRootAsCallRequest(payload, 0)
	if got := req.PayloadType(); got != RequestPayloadRepeatRequest {
		return nil, CallContext{}, fmt.Errorf("expected RepeatRequest payload, got %s", got.String())
	}
	var tab flatbuffers.Table
	if !req.Payload(&tab) {
		return nil, CallContext{}, fmt.Errorf("missing RepeatRequest payload")
	}
	out := &RepeatRequest{}
	out.Init(tab.Bytes, tab.Pos)
	return out, CallContext{RequestID: req.RequestId()}, nil
}

// BuildRepeatCallResponse wraps a RepeatResponse table offset in a CallResponse envelope.
func BuildRepeatCallResponse(call CallContext, builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) []byte {
	CallResponseStart(builder)
	CallResponseAddRequestId(builder, call.RequestID)
	CallResponseAddPayloadType(builder, ResponsePayloadRepeatResponse)
	CallResponseAddPayload(builder, payload)
	resp := CallResponseEnd(builder)
	builder.Finish(resp)
	return builder.FinishedBytes()
}

// DecodeRepeatResponse unwraps a CallResponse envelope and returns the RepeatResponse payload.
func DecodeRepeatResponse(payload []byte) (*RepeatResponse, CallContext, error) {
	resp := GetRootAsCallResponse(payload, 0)
	if got := resp.PayloadType(); got != ResponsePayloadRepeatResponse {
		return nil, CallContext{}, fmt.Errorf("expected RepeatResponse payload, got %s", got.String())
	}
	var tab flatbuffers.Table
	if !resp.Payload(&tab) {
		return nil, CallContext{}, fmt.Errorf("missing RepeatResponse payload")
	}
	out := &RepeatResponse{}
	out.Init(tab.Bytes, tab.Pos)
	return out, CallContext{RequestID: resp.RequestId()}, nil
}
