// Code generated by pluginart. DO NOT EDIT.
package repeat

import (
	"context"

	"github.com/dlahoza/pluginart/pkg/runtime"
	flatbuffers "github.com/google/flatbuffers/go"
)

// Client is the typed host-side client for the repeat plugin.
type Client struct {
	manager *runtime.PluginManager
	name    string
}

// NewClient creates a Client that calls pluginName via manager.
func NewClient(manager *runtime.PluginManager, pluginName string) *Client {
	return &Client{manager: manager, name: pluginName}
}

// Repeat calls the Repeat method on the plugin.
func (c *Client) Repeat(ctx context.Context, builder *flatbuffers.Builder, req flatbuffers.UOffsetT) (*RepeatResponse, error) {
	payload := BuildRepeatCallRequest(builder, req)
	raw, err := c.manager.Call(ctx, c.name, payload)
	if err != nil {
		return nil, err
	}
	resp, _, err := DecodeRepeatResponse(raw)
	return resp, err
}
