// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package repeat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RepeatRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsRepeatRequest(buf []byte, offset flatbuffers.UOffsetT) *RepeatRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RepeatRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishRepeatRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsRepeatRequest(buf []byte, offset flatbuffers.UOffsetT) *RepeatRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RepeatRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedRepeatRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *RepeatRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RepeatRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RepeatRequest) Input() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RepeatRequest) Count() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *RepeatRequest) MutateCount(n uint32) bool {
	return rcv._tab.MutateUint32Slot(6, n)
}

func RepeatRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RepeatRequestAddInput(builder *flatbuffers.Builder, input flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(input), 0)
}
func RepeatRequestAddCount(builder *flatbuffers.Builder, count uint32) {
	builder.PrependUint32Slot(1, count, 0)
}
func RepeatRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
