// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package repeat

import "strconv"

type RequestPayload byte

const (
	RequestPayloadNONE          RequestPayload = 0
	RequestPayloadRepeatRequest RequestPayload = 1
)

var EnumNamesRequestPayload = map[RequestPayload]string{
	RequestPayloadNONE:          "NONE",
	RequestPayloadRepeatRequest: "RepeatRequest",
}

var EnumValuesRequestPayload = map[string]RequestPayload{
	"NONE":          RequestPayloadNONE,
	"RepeatRequest": RequestPayloadRepeatRequest,
}

func (v RequestPayload) String() string {
	if s, ok := EnumNamesRequestPayload[v]; ok {
		return s
	}
	return "RequestPayload(" + strconv.FormatInt(int64(v), 10) + ")"
}
