// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { RequestPayload, unionToRequestPayload, unionListToRequestPayload } from '../echo/request-payload.js';


export class CallRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CallRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCallRequest(bb:flatbuffers.ByteBuffer, obj?:CallRequest):CallRequest {
  return (obj || new CallRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCallRequest(bb:flatbuffers.ByteBuffer, obj?:CallRequest):CallRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CallRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

requestId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

deadlineUnixMs():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

traceId():string|null
traceId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
traceId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

spanId():string|null
spanId(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
spanId(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

payloadType():RequestPayload {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : RequestPayload.NONE;
}

payload<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startCallRequest(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addRequestId(builder:flatbuffers.Builder, requestId:bigint) {
  builder.addFieldInt64(0, requestId, BigInt('0'));
}

static addDeadlineUnixMs(builder:flatbuffers.Builder, deadlineUnixMs:bigint) {
  builder.addFieldInt64(1, deadlineUnixMs, BigInt('0'));
}

static addTraceId(builder:flatbuffers.Builder, traceIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, traceIdOffset, 0);
}

static addSpanId(builder:flatbuffers.Builder, spanIdOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, spanIdOffset, 0);
}

static addPayloadType(builder:flatbuffers.Builder, payloadType:RequestPayload) {
  builder.addFieldInt8(4, payloadType, RequestPayload.NONE);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, payloadOffset, 0);
}

static endCallRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishCallRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedCallRequestBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createCallRequest(builder:flatbuffers.Builder, requestId:bigint, deadlineUnixMs:bigint, traceIdOffset:flatbuffers.Offset, spanIdOffset:flatbuffers.Offset, payloadType:RequestPayload, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  CallRequest.startCallRequest(builder);
  CallRequest.addRequestId(builder, requestId);
  CallRequest.addDeadlineUnixMs(builder, deadlineUnixMs);
  CallRequest.addTraceId(builder, traceIdOffset);
  CallRequest.addSpanId(builder, spanIdOffset);
  CallRequest.addPayloadType(builder, payloadType);
  CallRequest.addPayload(builder, payloadOffset);
  return CallRequest.endCallRequest(builder);
}
}
