// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class EchoRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):EchoRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsEchoRequest(bb:flatbuffers.ByteBuffer, obj?:EchoRequest):EchoRequest {
  return (obj || new EchoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsEchoRequest(bb:flatbuffers.ByteBuffer, obj?:EchoRequest):EchoRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new EchoRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

input():string|null
input(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
input(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startEchoRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addInput(builder:flatbuffers.Builder, inputOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, inputOffset, 0);
}

static endEchoRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createEchoRequest(builder:flatbuffers.Builder, inputOffset:flatbuffers.Offset):flatbuffers.Offset {
  EchoRequest.startEchoRequest(builder);
  EchoRequest.addInput(builder, inputOffset);
  return EchoRequest.endEchoRequest(builder);
}
}
