// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PluginError {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PluginError {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPluginError(bb:flatbuffers.ByteBuffer, obj?:PluginError):PluginError {
  return (obj || new PluginError()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPluginError(bb:flatbuffers.ByteBuffer, obj?:PluginError):PluginError {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PluginError()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

code():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

message():string|null
message(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
message(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

retry():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startPluginError(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addCode(builder:flatbuffers.Builder, code:number) {
  builder.addFieldInt16(0, code, 0);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static addRetry(builder:flatbuffers.Builder, retry:boolean) {
  builder.addFieldInt8(2, +retry, +false);
}

static endPluginError(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 6) // message
  return offset;
}

static createPluginError(builder:flatbuffers.Builder, code:number, messageOffset:flatbuffers.Offset, retry:boolean):flatbuffers.Offset {
  PluginError.startPluginError(builder);
  PluginError.addCode(builder, code);
  PluginError.addMessage(builder, messageOffset);
  PluginError.addRetry(builder, retry);
  return PluginError.endPluginError(builder);
}
}
