// Code generated by pluginart. DO NOT EDIT.
import * as flatbuffers from 'flatbuffers';
import { CallRequest } from './fb/echo/call-request';
import { CallResponse } from './fb/echo/call-response';
import { EchoRequest } from './fb/echo/echo-request';
import { EchoResponse } from './fb/echo/echo-response';
import { RequestPayload } from './fb/echo/request-payload';
import { ResponsePayload } from './fb/echo/response-payload';

export interface CallContext {
  requestId: bigint;
}

export function DecodeEchoRequest(payload: Buffer): { payload: EchoRequest; call: CallContext } {
  const request = CallRequest.getRootAsCallRequest(new flatbuffers.ByteBuffer(new Uint8Array(payload)));
  const got = request.payloadType();
  if (got !== RequestPayload.EchoRequest) {
    throw new Error(`expected EchoRequest payload, got ${got}`);
  }
  const out = request.payload(new EchoRequest()) as EchoRequest | null;
  if (!out) throw new Error('missing EchoRequest payload');
  return { payload: out, call: { requestId: request.requestId() } };
}

export function BuildEchoCallResponse(call: CallContext, builder: flatbuffers.Builder, payload: flatbuffers.Offset): Buffer {
  CallResponse.startCallResponse(builder);
  CallResponse.addRequestId(builder, call.requestId);
  CallResponse.addPayloadType(builder, ResponsePayload.EchoResponse);
  CallResponse.addPayload(builder, payload);
  const response = CallResponse.endCallResponse(builder);
  builder.finish(response);
  return Buffer.from(builder.asUint8Array());
}

