// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { EchoResponse } from '../echo/echo-response.js';


export enum ResponsePayload {
  NONE = 0,
  EchoResponse = 1
}

export function unionToResponsePayload(
  type: ResponsePayload,
  accessor: (obj:EchoResponse) => EchoResponse|null
): EchoResponse|null {
  switch(ResponsePayload[type]) {
    case 'NONE': return null; 
    case 'EchoResponse': return accessor(new EchoResponse())! as EchoResponse;
    default: return null;
  }
}

export function unionListToResponsePayload(
  type: ResponsePayload, 
  accessor: (index: number, obj:EchoResponse) => EchoResponse|null, 
  index: number
): EchoResponse|null {
  switch(ResponsePayload[type]) {
    case 'NONE': return null; 
    case 'EchoResponse': return accessor(index, new EchoResponse())! as EchoResponse;
    default: return null;
  }
}
