# Code generated by pluginart. DO NOT EDIT.
from dataclasses import dataclass

try:
    from .repeat import CallRequest, CallResponse, RepeatRequest, RepeatResponse, RequestPayload, ResponsePayload
except ImportError:
    from repeat import CallRequest, CallResponse, RepeatRequest, RepeatResponse, RequestPayload, ResponsePayload


@dataclass(frozen=True)
class CallContext:
    request_id: int


def BuildRepeatCallRequest(builder, payload: int) -> bytes:
    """Wrap a RepeatRequest table offset in a CallRequest envelope."""
    CallRequest.CallRequestStart(builder)
    CallRequest.CallRequestAddPayloadType(builder, RequestPayload.RequestPayload.RepeatRequest)
    CallRequest.CallRequestAddPayload(builder, payload)
    request = CallRequest.CallRequestEnd(builder)
    builder.Finish(request)
    return bytes(builder.Output())


def DecodeRepeatRequest(payload: bytes) -> tuple[RepeatRequest.RepeatRequest, CallContext]:
    """Unwrap a CallRequest envelope and return the RepeatRequest payload."""
    request = CallRequest.CallRequest.GetRootAs(bytearray(payload), 0)
    got = request.PayloadType()
    want = RequestPayload.RequestPayload.RepeatRequest
    if got != want:
        raise ValueError(f"expected RepeatRequest payload, got {got}")
    union_obj = request.Payload()
    if union_obj is None:
        raise ValueError("missing RepeatRequest payload")
    out = RepeatRequest.RepeatRequest()
    out.Init(union_obj.Bytes, union_obj.Pos)
    return out, CallContext(request_id=request.RequestId())


def BuildRepeatCallResponse(call: CallContext, builder, payload: int) -> bytes:
    """Wrap a RepeatResponse table offset in a CallResponse envelope."""
    CallResponse.CallResponseStart(builder)
    CallResponse.CallResponseAddRequestId(builder, call.request_id)
    CallResponse.CallResponseAddPayloadType(builder, ResponsePayload.ResponsePayload.RepeatResponse)
    CallResponse.CallResponseAddPayload(builder, payload)
    response = CallResponse.CallResponseEnd(builder)
    builder.Finish(response)
    return bytes(builder.Output())


def DecodeRepeatResponse(payload: bytes) -> tuple[RepeatResponse.RepeatResponse, CallContext]:
    """Unwrap a CallResponse envelope and return the RepeatResponse payload."""
    response = CallResponse.CallResponse.GetRootAs(bytearray(payload), 0)
    got = response.PayloadType()
    want = ResponsePayload.ResponsePayload.RepeatResponse
    if got != want:
        raise ValueError(f"expected RepeatResponse payload, got {got}")
    union_obj = response.Payload()
    if union_obj is None:
        raise ValueError("missing RepeatResponse payload")
    out = RepeatResponse.RepeatResponse()
    out.Init(union_obj.Bytes, union_obj.Pos)
    return out, CallContext(request_id=response.RequestId())


