# Code generated by pluginart. DO NOT EDIT.
from pluginart import PluginManager

try:
    from .pluginart_helpers import BuildRepeatCallRequest, DecodeRepeatResponse
except ImportError:
    from pluginart_helpers import BuildRepeatCallRequest, DecodeRepeatResponse


class repeatClient:
    """Typed host-side client for the repeat plugin."""

    def __init__(self, manager: PluginManager, plugin_name: str) -> None:
        self._manager = manager
        self._plugin_name = plugin_name

    def Repeat(self, builder, payload: int):
        """Call Repeat on the plugin. payload is a RepeatRequest table offset."""
        raw = self._manager.call(self._plugin_name, BuildRepeatCallRequest(builder, payload))
        response, _ = DecodeRepeatResponse(raw)
        return response
