# automatically generated by the FlatBuffers compiler, do not modify

# namespace: echo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PluginError(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PluginError()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPluginError(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PluginError
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PluginError
    def Code(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # PluginError
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # PluginError
    def Retry(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def PluginErrorStart(builder):
    builder.StartObject(3)

def Start(builder):
    PluginErrorStart(builder)

def PluginErrorAddCode(builder, code):
    builder.PrependUint16Slot(0, code, 0)

def AddCode(builder, code):
    PluginErrorAddCode(builder, code)

def PluginErrorAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    PluginErrorAddMessage(builder, message)

def PluginErrorAddRetry(builder, retry):
    builder.PrependBoolSlot(2, retry, 0)

def AddRetry(builder, retry):
    PluginErrorAddRetry(builder, retry)

def PluginErrorEnd(builder):
    return builder.EndObject()

def End(builder):
    return PluginErrorEnd(builder)
