// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ResponsePayload, unionToResponsePayload, unionListToResponsePayload } from '../echo/response-payload.js';


export class CallResponse {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CallResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCallResponse(bb:flatbuffers.ByteBuffer, obj?:CallResponse):CallResponse {
  return (obj || new CallResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCallResponse(bb:flatbuffers.ByteBuffer, obj?:CallResponse):CallResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CallResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

requestId():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

payloadType():ResponsePayload {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ResponsePayload.NONE;
}

payload<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startCallResponse(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addRequestId(builder:flatbuffers.Builder, requestId:bigint) {
  builder.addFieldInt64(0, requestId, BigInt('0'));
}

static addPayloadType(builder:flatbuffers.Builder, payloadType:ResponsePayload) {
  builder.addFieldInt8(1, payloadType, ResponsePayload.NONE);
}

static addPayload(builder:flatbuffers.Builder, payloadOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, payloadOffset, 0);
}

static endCallResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCallResponse(builder:flatbuffers.Builder, requestId:bigint, payloadType:ResponsePayload, payloadOffset:flatbuffers.Offset):flatbuffers.Offset {
  CallResponse.startCallResponse(builder);
  CallResponse.addRequestId(builder, requestId);
  CallResponse.addPayloadType(builder, payloadType);
  CallResponse.addPayload(builder, payloadOffset);
  return CallResponse.endCallResponse(builder);
}
}
