// Code generated by pluginart. DO NOT EDIT.
package echo

import (
	"fmt"

	flatbuffers "github.com/google/flatbuffers/go"
)

// CallContext carries RPC envelope metadata between generated decode/build helpers.
type CallContext struct {
	RequestID uint64
}

// BuildEchoCallRequest wraps an EchoRequest table offset in a CallRequest envelope.
func BuildEchoCallRequest(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) []byte {
	CallRequestStart(builder)
	CallRequestAddPayloadType(builder, RequestPayloadEchoRequest)
	CallRequestAddPayload(builder, payload)
	req := CallRequestEnd(builder)
	builder.Finish(req)
	return builder.FinishedBytes()
}

// DecodeEchoRequest unwraps a CallRequest envelope and returns the EchoRequest payload.
func DecodeEchoRequest(payload []byte) (*EchoRequest, CallContext, error) {
	req := GetRootAsCallRequest(payload, 0)
	if got := req.PayloadType(); got != RequestPayloadEchoRequest {
		return nil, CallContext{}, fmt.Errorf("expected EchoRequest payload, got %s", got.String())
	}
	var tab flatbuffers.Table
	if !req.Payload(&tab) {
		return nil, CallContext{}, fmt.Errorf("missing EchoRequest payload")
	}
	out := &EchoRequest{}
	out.Init(tab.Bytes, tab.Pos)
	return out, CallContext{RequestID: req.RequestId()}, nil
}

// BuildEchoCallResponse wraps an EchoResponse table offset in a CallResponse envelope.
func BuildEchoCallResponse(call CallContext, builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) []byte {
	CallResponseStart(builder)
	CallResponseAddRequestId(builder, call.RequestID)
	CallResponseAddPayloadType(builder, ResponsePayloadEchoResponse)
	CallResponseAddPayload(builder, payload)
	resp := CallResponseEnd(builder)
	builder.Finish(resp)
	return builder.FinishedBytes()
}

// DecodeEchoResponse unwraps a CallResponse envelope and returns the EchoResponse payload.
func DecodeEchoResponse(payload []byte) (*EchoResponse, CallContext, error) {
	resp := GetRootAsCallResponse(payload, 0)
	if got := resp.PayloadType(); got != ResponsePayloadEchoResponse {
		return nil, CallContext{}, fmt.Errorf("expected EchoResponse payload, got %s", got.String())
	}
	var tab flatbuffers.Table
	if !resp.Payload(&tab) {
		return nil, CallContext{}, fmt.Errorf("missing EchoResponse payload")
	}
	out := &EchoResponse{}
	out.Init(tab.Bytes, tab.Pos)
	return out, CallContext{RequestID: resp.RequestId()}, nil
}
