// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { EchoRequest } from '../echo/echo-request.js';


export enum RequestPayload {
  NONE = 0,
  EchoRequest = 1
}

export function unionToRequestPayload(
  type: RequestPayload,
  accessor: (obj:EchoRequest) => EchoRequest|null
): EchoRequest|null {
  switch(RequestPayload[type]) {
    case 'NONE': return null; 
    case 'EchoRequest': return accessor(new EchoRequest())! as EchoRequest;
    default: return null;
  }
}

export function unionListToRequestPayload(
  type: RequestPayload, 
  accessor: (index: number, obj:EchoRequest) => EchoRequest|null, 
  index: number
): EchoRequest|null {
  switch(RequestPayload[type]) {
    case 'NONE': return null; 
    case 'EchoRequest': return accessor(index, new EchoRequest())! as EchoRequest;
    default: return null;
  }
}
