# automatically generated by the FlatBuffers compiler, do not modify

# namespace: echo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EchoResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EchoResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEchoResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EchoResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EchoResponse
    def Output(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EchoResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    EchoResponseStart(builder)

def EchoResponseAddOutput(builder, output):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(output), 0)

def AddOutput(builder, output):
    EchoResponseAddOutput(builder, output)

def EchoResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return EchoResponseEnd(builder)
