# automatically generated by the FlatBuffers compiler, do not modify

# namespace: echo

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CallRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CallRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCallRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CallRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallRequest
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CallRequest
    def DeadlineUnixMs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # CallRequest
    def TraceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CallRequest
    def SpanId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CallRequest
    def PayloadType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CallRequest
    def Payload(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def CallRequestStart(builder):
    builder.StartObject(6)

def Start(builder):
    CallRequestStart(builder)

def CallRequestAddRequestId(builder, requestId):
    builder.PrependUint64Slot(0, requestId, 0)

def AddRequestId(builder, requestId):
    CallRequestAddRequestId(builder, requestId)

def CallRequestAddDeadlineUnixMs(builder, deadlineUnixMs):
    builder.PrependInt64Slot(1, deadlineUnixMs, 0)

def AddDeadlineUnixMs(builder, deadlineUnixMs):
    CallRequestAddDeadlineUnixMs(builder, deadlineUnixMs)

def CallRequestAddTraceId(builder, traceId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(traceId), 0)

def AddTraceId(builder, traceId):
    CallRequestAddTraceId(builder, traceId)

def CallRequestAddSpanId(builder, spanId):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(spanId), 0)

def AddSpanId(builder, spanId):
    CallRequestAddSpanId(builder, spanId)

def CallRequestAddPayloadType(builder, payloadType):
    builder.PrependUint8Slot(4, payloadType, 0)

def AddPayloadType(builder, payloadType):
    CallRequestAddPayloadType(builder, payloadType)

def CallRequestAddPayload(builder, payload):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(payload), 0)

def AddPayload(builder, payload):
    CallRequestAddPayload(builder, payload)

def CallRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return CallRequestEnd(builder)
