// Code generated by pluginart. DO NOT EDIT.
import * as net from 'net';
import { connectTo, callPlugin, FrameReader } from './pluginart_wire';

export class echoClient {
  private sock: net.Socket;
  private reader: FrameReader;

  private constructor(sock: net.Socket, reader: FrameReader) {
    this.sock   = sock;
    this.reader = reader;
  }

  static async connect(opts: { sockPath?: string; host?: string; port?: number }): Promise<echoClient> {
    const { sock, reader } = await connectTo(opts, 'echo');
    return new echoClient(sock, reader);
  }

  close(): void { this.sock.destroy(); }

  /** Call Echo on the plugin. payload is a raw FlatBuffers EchoRequest. */
  async Echo(payload: Buffer): Promise<Buffer> {
    return callPlugin(this.sock, this.reader, payload);
  }
}
