// Code generated by pluginart. DO NOT EDIT.
import { PluginManager } from 'pluginart';

export class echoClient {
  constructor(private manager: PluginManager, private pluginName: string) {}

  /** Call Echo on the plugin. payload is a full schema CallRequest FlatBuffer. */
  async Echo(payload: Buffer): Promise<Buffer> {
    return this.manager.call(this.pluginName, payload);
  }
}
