version = 1

[defaults]
startup_timeout     = "5s"
shutdown_timeout    = "5s"
health_interval     = "30s"
max_restarts        = 3
restart_backoff_max = "10s"
max_message_bytes   = 1048576

[[plugins]]
name = "echo"
type = "binary"
path = "../plugin-go/plugin-go"
transport = "tcp"
contract_hash = "sha256:094f99745014e0e307ad2b73394a45887059d3ce7fcda59fbd741f77e7904a14"

[[plugins]]
name = "echo-py"
type = "binary"
path = "python3"
args = ["../plugin-py/plugin.py"]
transport = "tcp"
contract_hash = "sha256:094f99745014e0e307ad2b73394a45887059d3ce7fcda59fbd741f77e7904a14"

[plugins.env]
PYTHONPATH = "../../runtimes/python:../plugin-py:../plugin-py/plugin"

[[plugins]]
name = "echo-ts"
type = "binary"
path = "node"
args = ["../plugin-ts/dist/plugin.js"]
transport = "tcp"
contract_hash = "sha256:094f99745014e0e307ad2b73394a45887059d3ce7fcda59fbd741f77e7904a14"
