// Code generated by pluginart. DO NOT EDIT.
// Wire protocol: framing, FlatBuffers handshake, serve() and connectTo() helpers.
import * as net from 'net';
import * as flatbuffers from 'flatbuffers';

const MAGIC    = Buffer.from([0x50, 0x4c, 0x47, 0x4e]); // PLGN
const HDR_SIZE = 9; // 4 magic + 4 length + 1 flags

const MSG_HANDSHAKE_REQUEST  = 0x01;
const MSG_HANDSHAKE_RESPONSE = 0x02;
export const MSG_CALL_REQUEST  = 0x03;
export const MSG_CALL_RESPONSE = 0x04;
export const MSG_PLUGIN_ERROR  = 0x05;
const MSG_CANCEL = 0x06;
const MSG_PING   = 0x07;
const MSG_PONG   = 0x08;

export const CONTRACT_HASH = 'sha256:094f99745014e0e307ad2b73394a45887059d3ce7fcda59fbd741f77e7904a14';

export interface Frame { flags: number; payload: Buffer; }

export class FrameReader {
  private buf = Buffer.alloc(0);
  private pending: Array<(f: Frame) => void> = [];

  feed(chunk: Buffer): void {
    this.buf = Buffer.concat([this.buf, chunk]);
    this.flush();
  }

  private flush(): void {
    while (this.buf.length >= HDR_SIZE) {
      if (!this.buf.subarray(0, 4).equals(MAGIC)) throw new Error('bad magic');
      const length = this.buf.readUInt32LE(4);
      if (this.buf.length < HDR_SIZE + length) break;
      const flags   = this.buf.readUInt8(8);
      const payload = Buffer.from(this.buf.subarray(HDR_SIZE, HDR_SIZE + length));
      this.buf = this.buf.subarray(HDR_SIZE + length);
      this.pending.shift()?.({ flags, payload });
    }
  }

  next(): Promise<Frame> {
    return new Promise((resolve) => { this.pending.push(resolve); this.flush(); });
  }
}

export function sendFrame(sock: net.Socket, flags: number, payload: Buffer): void {
  const hdr = Buffer.allocUnsafe(HDR_SIZE);
  MAGIC.copy(hdr, 0);
  hdr.writeUInt32LE(payload.length, 4);
  hdr.writeUInt8(flags, 8);
  sock.write(Buffer.concat([hdr, payload]));
}

function buildHandshakeRequest(contractHash: string, pluginName: string): Buffer {
  const builder = new flatbuffers.Builder(128);
  const ch = builder.createString(contractHash);
  const pn = builder.createString(pluginName);
  builder.startObject(3);
  builder.addFieldOffset(0, ch, 0);
  builder.addFieldOffset(1, pn, 0);
  builder.addFieldInt16(2, 1, 0);
  const root = builder.endObject();
  builder.finish(root);
  return Buffer.from(builder.asUint8Array());
}

function parseHandshakeResponse(payload: Buffer): { ok: boolean; error: string } {
  const bb = new flatbuffers.ByteBuffer(new Uint8Array(payload));
  const pos    = bb.readInt32(bb.position()) + bb.position();
  const okOff  = bb.__offset(pos, 4);
  const ok     = okOff ? bb.readInt8(pos + okOff) !== 0 : false;
  const errOff = bb.__offset(pos, 6);
  const error  = errOff ? ((bb.__string(pos + errOff) as string) ?? '') : '';
  return { ok, error };
}

function parseHandshakeRequest(payload: Buffer): string {
  const bb    = new flatbuffers.ByteBuffer(new Uint8Array(payload));
  const pos   = bb.readInt32(bb.position()) + bb.position();
  const chOff = bb.__offset(pos, 4);
  return chOff ? ((bb.__string(pos + chOff) as string) ?? '') : '';
}

function buildHandshakeResponse(ok: boolean, error = ''): Buffer {
  const builder = new flatbuffers.Builder(64);
  const errOff  = error ? builder.createString(error) : 0;
  builder.startObject(2);
  builder.addFieldInt8(0, ok ? 1 : 0, 0);
  if (errOff) builder.addFieldOffset(1, errOff, 0);
  const root = builder.endObject();
  builder.finish(root);
  return Buffer.from(builder.asUint8Array());
}

export async function connectTo(
  opts: { sockPath?: string; host?: string; port?: number },
  pluginName = '',
): Promise<{ sock: net.Socket; reader: FrameReader }> {
  const sock = await new Promise<net.Socket>((resolve, reject) => {
    let s: net.Socket;
    if (opts.sockPath) {
      s = net.createConnection({ path: opts.sockPath }, () => resolve(s));
    } else if (opts.host && opts.port) {
      s = net.createConnection({ host: opts.host, port: opts.port }, () => resolve(s));
    } else {
      reject(new Error('provide sockPath or host+port'));
      return;
    }
    s.once('error', reject);
  });

  const reader = new FrameReader();
  sock.on('data', (chunk: Buffer) => reader.feed(chunk));

  sendFrame(sock, MSG_HANDSHAKE_REQUEST, buildHandshakeRequest(CONTRACT_HASH, pluginName));
  const frame = await reader.next();
  if (frame.flags !== MSG_HANDSHAKE_RESPONSE) throw new Error('unexpected frame: ' + frame.flags);
  const { ok, error } = parseHandshakeResponse(frame.payload);
  if (!ok) throw new Error('handshake rejected: ' + error);

  return { sock, reader };
}

export async function callPlugin(sock: net.Socket, reader: FrameReader, payload: Buffer): Promise<Buffer> {
  sendFrame(sock, MSG_CALL_REQUEST, payload);
  const frame = await reader.next();
  if (frame.flags === MSG_PLUGIN_ERROR) throw new Error('plugin error: ' + frame.payload.toString());
  if (frame.flags !== MSG_CALL_RESPONSE) throw new Error('unexpected frame: ' + frame.flags);
  return frame.payload;
}

async function handleConn(
  sock: net.Socket,
  handler: (payload: Buffer) => Buffer | Promise<Buffer>,
): Promise<void> {
  const reader = new FrameReader();
  sock.on('data', (chunk: Buffer) => reader.feed(chunk));

  try {
    const hsFrame = await reader.next();
    if (hsFrame.flags !== MSG_HANDSHAKE_REQUEST) return;
    const contractHash = parseHandshakeRequest(hsFrame.payload);
    if (contractHash !== CONTRACT_HASH) {
      sendFrame(sock, MSG_HANDSHAKE_RESPONSE,
        buildHandshakeResponse(false, 'contract mismatch: got ' + contractHash));
      sock.destroy();
      return;
    }
    sendFrame(sock, MSG_HANDSHAKE_RESPONSE, buildHandshakeResponse(true));

    while (true) {
      const frame = await reader.next();
      if (frame.flags === MSG_CALL_REQUEST) {
        try {
          sendFrame(sock, MSG_CALL_RESPONSE, await handler(frame.payload));
        } catch (err) {
          sendFrame(sock, MSG_PLUGIN_ERROR,
            Buffer.from(err instanceof Error ? err.message : String(err)));
        }
      } else if (frame.flags === MSG_PING) {
        sendFrame(sock, MSG_PONG, frame.payload);
      } else if (frame.flags === MSG_CANCEL) {
        // best-effort; ignore
      } else {
        break;
      }
    }
  } catch {
    // connection closed
  } finally {
    sock.destroy();
  }
}

export function serve(handler: (payload: Buffer) => Buffer | Promise<Buffer>): void {
  const sockPath = process.env['PLUGIN_SOCKET'] ?? '';
  const addrStr  = process.env['PLUGIN_ADDR'] ?? '';

  let server: net.Server;
  if (sockPath) {
    server = net.createServer((sock) => { void handleConn(sock, handler); });
    server.listen(sockPath, () => { process.stdout.write('READY\n'); });
  } else if (addrStr) {
    const lastColon = addrStr.lastIndexOf(':');
    const host = addrStr.slice(0, lastColon);
    const port = parseInt(addrStr.slice(lastColon + 1), 10);
    server = net.createServer((sock) => { void handleConn(sock, handler); });
    server.listen(port, host, () => { process.stdout.write('READY\n'); });
  } else {
    process.stderr.write('PLUGIN_SOCKET or PLUGIN_ADDR must be set\n');
    process.exit(1);
  }
}
