# automatically generated by the FlatBuffers compiler, do not modify

# namespace: repeat

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RepeatRequest(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RepeatRequest()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRepeatRequest(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RepeatRequest
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RepeatRequest
    def Input(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # RepeatRequest
    def Count(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def RepeatRequestStart(builder):
    builder.StartObject(2)

def Start(builder):
    RepeatRequestStart(builder)

def RepeatRequestAddInput(builder, input):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(input), 0)

def AddInput(builder, input):
    RepeatRequestAddInput(builder, input)

def RepeatRequestAddCount(builder, count):
    builder.PrependUint32Slot(1, count, 0)

def AddCount(builder, count):
    RepeatRequestAddCount(builder, count)

def RepeatRequestEnd(builder):
    return builder.EndObject()

def End(builder):
    return RepeatRequestEnd(builder)
