// Code generated by pluginart. DO NOT EDIT.
import * as flatbuffers from 'flatbuffers';
import { CallRequest } from './fb/repeat/call-request';
import { CallResponse } from './fb/repeat/call-response';
import { RepeatRequest } from './fb/repeat/repeat-request';
import { RepeatResponse } from './fb/repeat/repeat-response';
import { RequestPayload } from './fb/repeat/request-payload';
import { ResponsePayload } from './fb/repeat/response-payload';

export interface CallContext {
  requestId: bigint;
}

export function DecodeRepeatRequest(payload: Buffer): { payload: RepeatRequest; call: CallContext } {
  const request = CallRequest.getRootAsCallRequest(new flatbuffers.ByteBuffer(new Uint8Array(payload)));
  const got = request.payloadType();
  if (got !== RequestPayload.RepeatRequest) {
    throw new Error(`expected RepeatRequest payload, got ${got}`);
  }
  const out = request.payload(new RepeatRequest()) as RepeatRequest | null;
  if (!out) throw new Error('missing RepeatRequest payload');
  return { payload: out, call: { requestId: request.requestId() } };
}

export function BuildRepeatCallResponse(call: CallContext, builder: flatbuffers.Builder, payload: flatbuffers.Offset): Buffer {
  CallResponse.startCallResponse(builder);
  CallResponse.addRequestId(builder, call.requestId);
  CallResponse.addPayloadType(builder, ResponsePayload.RepeatResponse);
  CallResponse.addPayload(builder, payload);
  const response = CallResponse.endCallResponse(builder);
  builder.finish(response);
  return Buffer.from(builder.asUint8Array());
}

