// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pluginart

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HandshakeResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsHandshakeResponse(buf []byte, offset flatbuffers.UOffsetT) *HandshakeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HandshakeResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishHandshakeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHandshakeResponse(buf []byte, offset flatbuffers.UOffsetT) *HandshakeResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HandshakeResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHandshakeResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HandshakeResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HandshakeResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HandshakeResponse) Ok() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *HandshakeResponse) MutateOk(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func (rcv *HandshakeResponse) Error() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func HandshakeResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func HandshakeResponseAddOk(builder *flatbuffers.Builder, ok bool) {
	builder.PrependBoolSlot(0, ok, false)
}
func HandshakeResponseAddError(builder *flatbuffers.Builder, error flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(error), 0)
}
func HandshakeResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
