// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pluginart

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type HandshakeRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsHandshakeRequest(buf []byte, offset flatbuffers.UOffsetT) *HandshakeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &HandshakeRequest{}
	x.Init(buf, n+offset)
	return x
}

func FinishHandshakeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsHandshakeRequest(buf []byte, offset flatbuffers.UOffsetT) *HandshakeRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &HandshakeRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedHandshakeRequestBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *HandshakeRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *HandshakeRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *HandshakeRequest) ContractHash() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *HandshakeRequest) PluginName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *HandshakeRequest) ProtocolVersion() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 1
}

func (rcv *HandshakeRequest) MutateProtocolVersion(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func HandshakeRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func HandshakeRequestAddContractHash(builder *flatbuffers.Builder, contractHash flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(contractHash), 0)
}
func HandshakeRequestAddPluginName(builder *flatbuffers.Builder, pluginName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(pluginName), 0)
}
func HandshakeRequestAddProtocolVersion(builder *flatbuffers.Builder, protocolVersion uint16) {
	builder.PrependUint16Slot(2, protocolVersion, 1)
}
func HandshakeRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
