// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package pluginart

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PluginError struct {
	_tab flatbuffers.Table
}

func GetRootAsPluginError(buf []byte, offset flatbuffers.UOffsetT) *PluginError {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PluginError{}
	x.Init(buf, n+offset)
	return x
}

func FinishPluginErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsPluginError(buf []byte, offset flatbuffers.UOffsetT) *PluginError {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &PluginError{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedPluginErrorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *PluginError) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PluginError) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PluginError) Code() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *PluginError) MutateCode(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *PluginError) Message() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PluginError) Retry() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *PluginError) MutateRetry(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func PluginErrorStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func PluginErrorAddCode(builder *flatbuffers.Builder, code uint16) {
	builder.PrependUint16Slot(0, code, 0)
}
func PluginErrorAddMessage(builder *flatbuffers.Builder, message flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(message), 0)
}
func PluginErrorAddRetry(builder *flatbuffers.Builder, retry bool) {
	builder.PrependBoolSlot(2, retry, false)
}
func PluginErrorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
