package cmd

const schemaTmpl = `// {{.Name}}.fbs
// Edit this file to define your plugin's methods.
// Run: pluginart gen bindings --target host --lang go --schema ./schema/{{.Name}}.fbs
//      pluginart gen plugin --lang go --name {{.Name}} --schema ./schema/{{.Name}}.fbs

namespace {{.Name}};

// ── Step 1: Define one table per method input ─────────────────────────────

table ExampleRequest {
  input: string;
  // Add your fields here
}

// ── Step 2: Define one table per method output ────────────────────────────

table ExampleResponse {
  output: string;
  // Add your fields here
}

// ── Step 3: Register methods in these unions ──────────────────────────────
// Add new methods by adding new table pairs above and listing them here.

union RequestPayload  { ExampleRequest }
union ResponsePayload { ExampleResponse }

// ── Do not edit below this line ───────────────────────────────────────────

table CallRequest {
  request_id:       uint64;
  deadline_unix_ms: int64;
  trace_id:         string;
  span_id:          string;
  payload:          RequestPayload;
}

table CallResponse {
  request_id: uint64;
  payload:    ResponsePayload;
}

table ShmHandle { offset: uint64; length: uint64; }

table PluginError {
  code:    uint16;
  message: string;
  retry:   bool;
}

root_type CallRequest;
`

const clientTmpl = `// Code generated by pluginart. DO NOT EDIT.
package {{.Namespace}}

import (
	"context"

	"github.com/dlahoza/pluginart/pkg/runtime"
	flatbuffers "github.com/google/flatbuffers/go"
)

// Client is the typed host-side client for the {{.Namespace}} plugin.
type Client struct {
	manager *runtime.PluginManager
	name    string
}

// NewClient creates a Client that calls pluginName via manager.
func NewClient(manager *runtime.PluginManager, pluginName string) *Client {
	return &Client{manager: manager, name: pluginName}
}
{{range .Methods}}
// {{.Name}} calls the {{.Name}} method on the plugin.
func (c *Client) {{.Name}}(ctx context.Context, builder *flatbuffers.Builder, req flatbuffers.UOffsetT) (*{{.ResponseTable}}, error) {
	payload := Build{{.Name}}CallRequest(builder, req)
	raw, err := c.manager.Call(ctx, c.name, payload)
	if err != nil {
		return nil, err
	}
	resp, _, err := Decode{{.Name}}Response(raw)
	return resp, err
}
{{end}}`

const goEnvelopeHelpersTmpl = `// Code generated by pluginart. DO NOT EDIT.
package {{.Namespace}}

import (
	"fmt"

	flatbuffers "github.com/google/flatbuffers/go"
)

// CallContext carries RPC envelope metadata between generated decode/build helpers.
type CallContext struct {
	RequestID uint64
}
{{range .Methods}}
// Build{{.Name}}CallRequest wraps a {{.RequestTable}} table offset in a CallRequest envelope.
func Build{{.Name}}CallRequest(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) []byte {
	CallRequestStart(builder)
	CallRequestAddPayloadType(builder, RequestPayload{{.RequestTable}})
	CallRequestAddPayload(builder, payload)
	req := CallRequestEnd(builder)
	builder.Finish(req)
	return builder.FinishedBytes()
}

// Decode{{.Name}}Request unwraps a CallRequest envelope and returns the {{.RequestTable}} payload.
func Decode{{.Name}}Request(payload []byte) (*{{.RequestTable}}, CallContext, error) {
	req := GetRootAsCallRequest(payload, 0)
	if got := req.PayloadType(); got != RequestPayload{{.RequestTable}} {
		return nil, CallContext{}, fmt.Errorf("expected {{.RequestTable}} payload, got %s", got.String())
	}
	var tab flatbuffers.Table
	if !req.Payload(&tab) {
		return nil, CallContext{}, fmt.Errorf("missing {{.RequestTable}} payload")
	}
	out := &{{.RequestTable}}{}
	out.Init(tab.Bytes, tab.Pos)
	return out, CallContext{RequestID: req.RequestId()}, nil
}

// Build{{.Name}}CallResponse wraps a {{.ResponseTable}} table offset in a CallResponse envelope.
func Build{{.Name}}CallResponse(call CallContext, builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) []byte {
	CallResponseStart(builder)
	CallResponseAddRequestId(builder, call.RequestID)
	CallResponseAddPayloadType(builder, ResponsePayload{{.ResponseTable}})
	CallResponseAddPayload(builder, payload)
	resp := CallResponseEnd(builder)
	builder.Finish(resp)
	return builder.FinishedBytes()
}

// Decode{{.Name}}Response unwraps a CallResponse envelope and returns the {{.ResponseTable}} payload.
func Decode{{.Name}}Response(payload []byte) (*{{.ResponseTable}}, CallContext, error) {
	resp := GetRootAsCallResponse(payload, 0)
	if got := resp.PayloadType(); got != ResponsePayload{{.ResponseTable}} {
		return nil, CallContext{}, fmt.Errorf("expected {{.ResponseTable}} payload, got %s", got.String())
	}
	var tab flatbuffers.Table
	if !resp.Payload(&tab) {
		return nil, CallContext{}, fmt.Errorf("missing {{.ResponseTable}} payload")
	}
	out := &{{.ResponseTable}}{}
	out.Init(tab.Bytes, tab.Pos)
	return out, CallContext{RequestID: resp.RequestId()}, nil
}
{{end}}`

const goPluginEnvelopeHelpersTmpl = `// Code generated by pluginart. DO NOT EDIT.
package main

import (
	"fmt"

	flatbuffers "github.com/google/flatbuffers/go"
)

// CallContext carries RPC envelope metadata between generated decode/build helpers.
type CallContext struct {
	RequestID uint64
}
{{range .Methods}}
// Decode{{.Name}}Request unwraps a CallRequest envelope and returns the {{.RequestTable}} payload.
func Decode{{.Name}}Request(payload []byte) (*{{.RequestTable}}, CallContext, error) {
	req := GetRootAsCallRequest(payload, 0)
	if got := req.PayloadType(); got != RequestPayload{{.RequestTable}} {
		return nil, CallContext{}, fmt.Errorf("expected {{.RequestTable}} payload, got %s", got.String())
	}
	var tab flatbuffers.Table
	if !req.Payload(&tab) {
		return nil, CallContext{}, fmt.Errorf("missing {{.RequestTable}} payload")
	}
	out := &{{.RequestTable}}{}
	out.Init(tab.Bytes, tab.Pos)
	return out, CallContext{RequestID: req.RequestId()}, nil
}

// Build{{.Name}}CallResponse wraps a {{.ResponseTable}} table offset in a CallResponse envelope.
func Build{{.Name}}CallResponse(call CallContext, builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) []byte {
	CallResponseStart(builder)
	CallResponseAddRequestId(builder, call.RequestID)
	CallResponseAddPayloadType(builder, ResponsePayload{{.ResponseTable}})
	CallResponseAddPayload(builder, payload)
	resp := CallResponseEnd(builder)
	builder.Finish(resp)
	return builder.FinishedBytes()
}
{{end}}`

const goPluginBindingsHelpersTmpl = `// Code generated by pluginart. DO NOT EDIT.
package {{.Namespace}}

import (
	"fmt"

	flatbuffers "github.com/google/flatbuffers/go"
)

// CallContext carries RPC envelope metadata between generated decode/build helpers.
type CallContext struct {
	RequestID uint64
}
{{range .Methods}}
// Decode{{.Name}}Request unwraps a CallRequest envelope and returns the {{.RequestTable}} payload.
func Decode{{.Name}}Request(payload []byte) (*{{.RequestTable}}, CallContext, error) {
	req := GetRootAsCallRequest(payload, 0)
	if got := req.PayloadType(); got != RequestPayload{{.RequestTable}} {
		return nil, CallContext{}, fmt.Errorf("expected {{.RequestTable}} payload, got %s", got.String())
	}
	var tab flatbuffers.Table
	if !req.Payload(&tab) {
		return nil, CallContext{}, fmt.Errorf("missing {{.RequestTable}} payload")
	}
	out := &{{.RequestTable}}{}
	out.Init(tab.Bytes, tab.Pos)
	return out, CallContext{RequestID: req.RequestId()}, nil
}

// Build{{.Name}}CallResponse wraps a {{.ResponseTable}} table offset in a CallResponse envelope.
func Build{{.Name}}CallResponse(call CallContext, builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) []byte {
	CallResponseStart(builder)
	CallResponseAddRequestId(builder, call.RequestID)
	CallResponseAddPayloadType(builder, ResponsePayload{{.ResponseTable}})
	CallResponseAddPayload(builder, payload)
	resp := CallResponseEnd(builder)
	builder.Finish(resp)
	return builder.FinishedBytes()
}
{{end}}`

const contractTmpl = `// Code generated by pluginart. DO NOT EDIT.
package {{.Package}}

// ContractHash is the SHA-256 of the schema file used to generate this code.
// The pluginart runtime verifies this matches on every connection.
const ContractHash = "{{.Hash}}"
`

const pluginMainTmpl = `// Plugin entrypoint. Edit this file as needed.
package main

import (
	"fmt"
	"net"
	"os"

	"{{.Name}}-plugin/plugin/{{.Namespace}}"

	"github.com/dlahoza/pluginart/pkg/protocol"
)

func main() {
	var (
		ln  net.Listener
		err error
	)
	switch {
	case os.Getenv("PLUGIN_SOCKET") != "":
		ln, err = net.Listen("unix", os.Getenv("PLUGIN_SOCKET"))
	case os.Getenv("PLUGIN_ADDR") != "":
		ln, err = net.Listen("tcp", os.Getenv("PLUGIN_ADDR"))
	default:
		fmt.Fprintln(os.Stderr, "PLUGIN_SOCKET or PLUGIN_ADDR must be set")
		os.Exit(1)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "listen: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("READY")

	handler := &PluginHandler{}
	server := protocol.NewServer(ln, handler, {{.Namespace}}.ContractHash)
	if err := server.Serve(); err != nil {
		fmt.Fprintf(os.Stderr, "serve: %v\n", err)
		os.Exit(1)
	}
}
`

const pluginHandlerTmpl = `package main

import (
	"context"
	"fmt"
)

// PluginHandler implements the plugin logic. Edit this file.
type PluginHandler struct{}

// Handle is called for every incoming request.
// Use Decode<Method>Request and Build<Method>CallResponse helpers to avoid
// hand-writing the pluginart RPC envelope.
func (h *PluginHandler) Handle(ctx context.Context, payload []byte) ([]byte, error) {
	_ = ctx
	_ = payload
	// TODO: decode a method payload and return a response.
	return nil, fmt.Errorf("not implemented")
}
`

const pluginGomodTmpl = `module {{.Name}}-plugin

go 1.23

require (
	github.com/dlahoza/pluginart v0.2.2
	github.com/google/flatbuffers v25.12.19+incompatible
)
`

const pluginDockerfileTmpl = `FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o plugin .

FROM alpine:3.20
RUN adduser -D -u 1000 plugin
USER plugin
COPY --from=builder /app/plugin /plugin
ENTRYPOINT ["/plugin"]
`
