package cmd

const tsClientTmpl = `// Code generated by pluginart. DO NOT EDIT.
import * as net from 'net';
import * as flatbuffers from 'flatbuffers';

// ── Wire protocol ─────────────────────────────────────────────────────────────

const MAGIC = Buffer.from([0x50, 0x4c, 0x47, 0x4e]); // PLGN
const HDR_SIZE = 9; // 4 magic + 4 length + 1 flags

const MSG_HANDSHAKE_REQUEST  = 0x01;
const MSG_HANDSHAKE_RESPONSE = 0x02;
const MSG_CALL_REQUEST       = 0x03;
const MSG_CALL_RESPONSE      = 0x04;
const MSG_PLUGIN_ERROR       = 0x05;
const MSG_CANCEL             = 0x06;
const MSG_PING               = 0x07;
const MSG_PONG               = 0x08;

export const CONTRACT_HASH = '{{.ContractHash}}';

interface Frame { flags: number; payload: Buffer; }

function sendFrame(sock: net.Socket, flags: number, payload: Buffer): void {
  const hdr = Buffer.allocUnsafe(HDR_SIZE);
  MAGIC.copy(hdr, 0);
  hdr.writeUInt32LE(payload.length, 4);
  hdr.writeUInt8(flags, 8);
  sock.write(Buffer.concat([hdr, payload]));
}

class FrameReader {
  private buf = Buffer.alloc(0);
  private pending: Array<(f: Frame) => void> = [];

  feed(chunk: Buffer): void {
    this.buf = Buffer.concat([this.buf, chunk]);
    this.dispatch();
  }

  private dispatch(): void {
    while (this.buf.length >= HDR_SIZE) {
      if (!this.buf.subarray(0, 4).equals(MAGIC)) {
        throw new Error('bad magic');
      }
      const length = this.buf.readUInt32LE(4);
      if (this.buf.length < HDR_SIZE + length) break;
      const flags   = this.buf.readUInt8(8);
      const payload = this.buf.subarray(HDR_SIZE, HDR_SIZE + length);
      this.buf = this.buf.subarray(HDR_SIZE + length);
      const resolve = this.pending.shift();
      if (resolve) resolve({ flags, payload: Buffer.from(payload) });
    }
  }

  next(): Promise<Frame> {
    return new Promise((resolve) => {
      this.pending.push(resolve);
      this.dispatch();
    });
  }
}

function buildHandshakeRequest(contractHash: string, pluginName: string): Buffer {
  const builder = new flatbuffers.Builder(128);
  const ch = builder.createString(contractHash);
  const pn = builder.createString(pluginName);
  builder.startObject(3);
  builder.addFieldOffset(0, ch, 0);
  builder.addFieldOffset(1, pn, 0);
  builder.addFieldInt16(2, 1, 0);
  const root = builder.endObject();
  builder.finish(root);
  return Buffer.from(builder.asUint8Array());
}

function parseHandshakeResponse(payload: Buffer): { ok: boolean; error: string } {
  const bb = new flatbuffers.ByteBuffer(new Uint8Array(payload));
  const pos = bb.readInt32(bb.position()) + bb.position();
  const okOff = bb.__offset(pos, 4);
  const ok = okOff ? bb.readInt8(pos + okOff) !== 0 : false;
  const errOff = bb.__offset(pos, 6);
  const error = errOff ? bb.__string(pos + errOff) ?? '' : '';
  return { ok, error };
}

// ── Client ────────────────────────────────────────────────────────────────────

export class {{.Namespace}}Client {
  private sock: net.Socket;
  private reader: FrameReader;

  private constructor(sock: net.Socket) {
    this.sock = sock;
    this.reader = new FrameReader();
    sock.on('data', (chunk: Buffer) => this.reader.feed(chunk));
  }

  static async connect(opts: { sockPath?: string; host?: string; port?: number }): Promise<{{.Namespace}}Client> {
    const sock = await new Promise<net.Socket>((resolve, reject) => {
      let s: net.Socket;
      if (opts.sockPath) {
        s = net.createConnection({ path: opts.sockPath }, () => resolve(s));
      } else if (opts.host && opts.port) {
        s = net.createConnection({ host: opts.host, port: opts.port }, () => resolve(s));
      } else {
        reject(new Error('provide sockPath or host+port'));
        return;
      }
      s.once('error', reject);
    });

    const client = new {{.Namespace}}Client(sock);
    await client._handshake();
    return client;
  }

  private async _handshake(): Promise<void> {
    sendFrame(this.sock, MSG_HANDSHAKE_REQUEST, buildHandshakeRequest(CONTRACT_HASH, '{{.Namespace}}'));
    const frame = await this.reader.next();
    if (frame.flags !== MSG_HANDSHAKE_RESPONSE) {
      throw new Error('unexpected frame type during handshake: ' + frame.flags);
    }
    const { ok, error } = parseHandshakeResponse(frame.payload);
    if (!ok) throw new Error('handshake rejected: ' + error);
  }

  private async _call(payload: Buffer): Promise<Buffer> {
    sendFrame(this.sock, MSG_CALL_REQUEST, payload);
    const frame = await this.reader.next();
    if (frame.flags === MSG_PLUGIN_ERROR) {
      throw new Error('plugin error: ' + frame.payload.toString());
    }
    if (frame.flags !== MSG_CALL_RESPONSE) {
      throw new Error('unexpected frame type: ' + frame.flags);
    }
    return frame.payload;
  }

  close(): void { this.sock.destroy(); }
{{range .Methods}}
  /** Call {{.Name}} on the plugin. payload is a raw FlatBuffers {{.RequestTable}}. */
  async {{.Name}}(payload: Buffer): Promise<Buffer> {
    return this._call(payload);
  }
{{end}}}
`

const tsPluginTmpl = `// Code generated by pluginart. DO NOT EDIT.
import * as net from 'net';
import * as flatbuffers from 'flatbuffers';
import { handle } from './handler';

// ── Wire protocol ─────────────────────────────────────────────────────────────

const MAGIC = Buffer.from([0x50, 0x4c, 0x47, 0x4e]); // PLGN
const HDR_SIZE = 9;

const MSG_HANDSHAKE_REQUEST  = 0x01;
const MSG_HANDSHAKE_RESPONSE = 0x02;
const MSG_CALL_REQUEST       = 0x03;
const MSG_CALL_RESPONSE      = 0x04;
const MSG_PLUGIN_ERROR       = 0x05;
const MSG_CANCEL             = 0x06;
const MSG_PING               = 0x07;
const MSG_PONG               = 0x08;

const CONTRACT_HASH = '{{.ContractHash}}';

interface Frame { flags: number; payload: Buffer; }

function sendFrame(sock: net.Socket, flags: number, payload: Buffer): void {
  const hdr = Buffer.allocUnsafe(HDR_SIZE);
  MAGIC.copy(hdr, 0);
  hdr.writeUInt32LE(payload.length, 4);
  hdr.writeUInt8(flags, 8);
  sock.write(Buffer.concat([hdr, payload]));
}

class FrameReader {
  private buf = Buffer.alloc(0);
  private pending: Array<(f: Frame) => void> = [];

  feed(chunk: Buffer): void {
    this.buf = Buffer.concat([this.buf, chunk]);
    this.dispatch();
  }

  private dispatch(): void {
    while (this.buf.length >= HDR_SIZE) {
      if (!this.buf.subarray(0, 4).equals(MAGIC)) throw new Error('bad magic');
      const length = this.buf.readUInt32LE(4);
      if (this.buf.length < HDR_SIZE + length) break;
      const flags   = this.buf.readUInt8(8);
      const payload = this.buf.subarray(HDR_SIZE, HDR_SIZE + length);
      this.buf = this.buf.subarray(HDR_SIZE + length);
      const resolve = this.pending.shift();
      if (resolve) resolve({ flags, payload: Buffer.from(payload) });
    }
  }

  next(): Promise<Frame> {
    return new Promise((resolve) => {
      this.pending.push(resolve);
      this.dispatch();
    });
  }
}

function parseHandshakeRequest(payload: Buffer): { contractHash: string; pluginName: string } {
  const bb = new flatbuffers.ByteBuffer(new Uint8Array(payload));
  const pos = bb.readInt32(bb.position()) + bb.position();
  const chOff = bb.__offset(pos, 4);
  const contractHash = chOff ? bb.__string(pos + chOff) ?? '' : '';
  const pnOff = bb.__offset(pos, 6);
  const pluginName = pnOff ? bb.__string(pos + pnOff) ?? '' : '';
  return { contractHash, pluginName };
}

function buildHandshakeResponse(ok: boolean, error: string = ''): Buffer {
  const builder = new flatbuffers.Builder(64);
  const errOff = error ? builder.createString(error) : 0;
  builder.startObject(2);
  builder.addFieldInt8(0, ok ? 1 : 0, 0);
  if (errOff) builder.addFieldOffset(1, errOff, 0);
  const root = builder.endObject();
  builder.finish(root);
  return Buffer.from(builder.asUint8Array());
}

// ── Connection handler ────────────────────────────────────────────────────────

async function handleConn(sock: net.Socket): Promise<void> {
  const reader = new FrameReader();
  sock.on('data', (chunk: Buffer) => reader.feed(chunk));

  try {
    const hsFrame = await reader.next();
    if (hsFrame.flags !== MSG_HANDSHAKE_REQUEST) return;

    const { contractHash } = parseHandshakeRequest(hsFrame.payload);
    if (contractHash !== CONTRACT_HASH) {
      sendFrame(sock, MSG_HANDSHAKE_RESPONSE, buildHandshakeResponse(false, 'contract mismatch: got ' + contractHash));
      sock.destroy();
      return;
    }
    sendFrame(sock, MSG_HANDSHAKE_RESPONSE, buildHandshakeResponse(true));

    while (true) {
      const frame = await reader.next();
      if (frame.flags === MSG_CALL_REQUEST) {
        try {
          const resp = handle(frame.payload);
          sendFrame(sock, MSG_CALL_RESPONSE, resp);
        } catch (err) {
          const msg = err instanceof Error ? err.message : String(err);
          sendFrame(sock, MSG_PLUGIN_ERROR, Buffer.from(msg));
        }
      } else if (frame.flags === MSG_PING) {
        sendFrame(sock, MSG_PONG, frame.payload);
      } else if (frame.flags === MSG_CANCEL) {
        // best-effort; ignore
      } else {
        break;
      }
    }
  } catch {
    // connection closed
  } finally {
    sock.destroy();
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────

function main(): void {
  const sockPath = process.env['PLUGIN_SOCKET'] ?? '';
  const addrStr  = process.env['PLUGIN_ADDR'] ?? '';

  let server: net.Server;

  if (sockPath) {
    server = net.createServer((sock) => { void handleConn(sock); });
    server.listen(sockPath, () => {
      process.stdout.write('READY\n');
    });
  } else if (addrStr) {
    const lastColon = addrStr.lastIndexOf(':');
    const host = addrStr.slice(0, lastColon);
    const port = parseInt(addrStr.slice(lastColon + 1), 10);
    server = net.createServer((sock) => { void handleConn(sock); });
    server.listen(port, host, () => {
      process.stdout.write('READY\n');
    });
  } else {
    process.stderr.write('PLUGIN_SOCKET or PLUGIN_ADDR must be set\n');
    process.exit(1);
  }
}

main();
`

const tsHandlerTmpl = `// Edit this file to implement your plugin logic.
import { Buffer } from 'buffer';

export function handle(payload: Buffer): Buffer {
  // payload is a raw FlatBuffers CallRequest.
  // Return raw FlatBuffers CallResponse bytes.
  throw new Error('not implemented');
}
`

const tsPackageJSONTmpl = `{
  "name": "{{.Name}}-plugin",
  "version": "0.1.0",
  "main": "dist/plugin.js",
  "scripts": {
    "build": "tsc",
    "start": "node dist/plugin.js"
  },
  "dependencies": {
    "flatbuffers": "^25.2.10"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/node": "^22.0.0"
  }
}
`

const tsTsconfigTmpl = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "outDir": "dist",
    "strict": true,
    "esModuleInterop": true
  },
  "include": ["*.ts"]
}
`

const tsDockerfileTmpl = `FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
ENTRYPOINT ["node", "dist/plugin.js"]
`
