package cmd

const pyPluginTmpl = `# Plugin entrypoint. Edit this file as needed.
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent / 'plugin'))

from pluginart import serve
from contract import CONTRACT_HASH
from handler import handle

if __name__ == '__main__':
    serve(handle, contract_hash=CONTRACT_HASH)
`

const pyClientTmpl = `# Code generated by pluginart. DO NOT EDIT.
from pluginart import PluginManager

try:
    from .pluginart_helpers import {{range $i, $m := .Methods}}{{if $i}}, {{end}}Build{{.Name}}CallRequest, Decode{{.Name}}Response{{end}}
except ImportError:
    from pluginart_helpers import {{range $i, $m := .Methods}}{{if $i}}, {{end}}Build{{.Name}}CallRequest, Decode{{.Name}}Response{{end}}


class {{.Namespace}}Client:
    """Typed host-side client for the {{.Namespace}} plugin."""

    def __init__(self, manager: PluginManager, plugin_name: str) -> None:
        self._manager = manager
        self._plugin_name = plugin_name
{{range .Methods}}
    def {{.Name}}(self, builder, payload: int):
        """Call {{.Name}} on the plugin. payload is a {{.RequestTable}} table offset."""
        raw = self._manager.call(self._plugin_name, Build{{.Name}}CallRequest(builder, payload))
        response, _ = Decode{{.Name}}Response(raw)
        return response
{{end}}`

const pyEnvelopeHelpersTmpl = `# Code generated by pluginart. DO NOT EDIT.
from dataclasses import dataclass

try:
    from .{{.Namespace}} import CallRequest, CallResponse, {{range $i, $m := .Methods}}{{if $i}}, {{end}}{{.RequestTable}}, {{.ResponseTable}}{{end}}, RequestPayload, ResponsePayload
except ImportError:
    from {{.Namespace}} import CallRequest, CallResponse, {{range $i, $m := .Methods}}{{if $i}}, {{end}}{{.RequestTable}}, {{.ResponseTable}}{{end}}, RequestPayload, ResponsePayload


@dataclass(frozen=True)
class CallContext:
    request_id: int

{{range .Methods}}
def Build{{.Name}}CallRequest(builder, payload: int) -> bytes:
    """Wrap a {{.RequestTable}} table offset in a CallRequest envelope."""
    CallRequest.CallRequestStart(builder)
    CallRequest.CallRequestAddPayloadType(builder, RequestPayload.RequestPayload.{{.RequestTable}})
    CallRequest.CallRequestAddPayload(builder, payload)
    request = CallRequest.CallRequestEnd(builder)
    builder.Finish(request)
    return bytes(builder.Output())


def Decode{{.Name}}Request(payload: bytes) -> tuple[{{.RequestTable}}.{{.RequestTable}}, CallContext]:
    """Unwrap a CallRequest envelope and return the {{.RequestTable}} payload."""
    request = CallRequest.CallRequest.GetRootAs(bytearray(payload), 0)
    got = request.PayloadType()
    want = RequestPayload.RequestPayload.{{.RequestTable}}
    if got != want:
        raise ValueError(f"expected {{.RequestTable}} payload, got {got}")
    union_obj = request.Payload()
    if union_obj is None:
        raise ValueError("missing {{.RequestTable}} payload")
    out = {{.RequestTable}}.{{.RequestTable}}()
    out.Init(union_obj.Bytes, union_obj.Pos)
    return out, CallContext(request_id=request.RequestId())


def Build{{.Name}}CallResponse(call: CallContext, builder, payload: int) -> bytes:
    """Wrap a {{.ResponseTable}} table offset in a CallResponse envelope."""
    CallResponse.CallResponseStart(builder)
    CallResponse.CallResponseAddRequestId(builder, call.request_id)
    CallResponse.CallResponseAddPayloadType(builder, ResponsePayload.ResponsePayload.{{.ResponseTable}})
    CallResponse.CallResponseAddPayload(builder, payload)
    response = CallResponse.CallResponseEnd(builder)
    builder.Finish(response)
    return bytes(builder.Output())


def Decode{{.Name}}Response(payload: bytes) -> tuple[{{.ResponseTable}}.{{.ResponseTable}}, CallContext]:
    """Unwrap a CallResponse envelope and return the {{.ResponseTable}} payload."""
    response = CallResponse.CallResponse.GetRootAs(bytearray(payload), 0)
    got = response.PayloadType()
    want = ResponsePayload.ResponsePayload.{{.ResponseTable}}
    if got != want:
        raise ValueError(f"expected {{.ResponseTable}} payload, got {got}")
    union_obj = response.Payload()
    if union_obj is None:
        raise ValueError("missing {{.ResponseTable}} payload")
    out = {{.ResponseTable}}.{{.ResponseTable}}()
    out.Init(union_obj.Bytes, union_obj.Pos)
    return out, CallContext(request_id=response.RequestId())


{{end}}`

const pyPluginEnvelopeHelpersTmpl = `# Code generated by pluginart. DO NOT EDIT.
from dataclasses import dataclass

from fb.{{.Namespace}} import CallRequest, CallResponse, {{range $i, $m := .Methods}}{{if $i}}, {{end}}{{.RequestTable}}, {{.ResponseTable}}{{end}}, RequestPayload, ResponsePayload


@dataclass(frozen=True)
class CallContext:
    request_id: int

{{range .Methods}}
def Decode{{.Name}}Request(payload: bytes) -> tuple[{{.RequestTable}}.{{.RequestTable}}, CallContext]:
    """Unwrap a CallRequest envelope and return the {{.RequestTable}} payload."""
    request = CallRequest.CallRequest.GetRootAs(bytearray(payload), 0)
    got = request.PayloadType()
    want = RequestPayload.RequestPayload.{{.RequestTable}}
    if got != want:
        raise ValueError(f"expected {{.RequestTable}} payload, got {got}")
    union_obj = request.Payload()
    if union_obj is None:
        raise ValueError("missing {{.RequestTable}} payload")
    out = {{.RequestTable}}.{{.RequestTable}}()
    out.Init(union_obj.Bytes, union_obj.Pos)
    return out, CallContext(request_id=request.RequestId())


def Build{{.Name}}CallResponse(call: CallContext, builder, payload: int) -> bytes:
    """Wrap a {{.ResponseTable}} table offset in a CallResponse envelope."""
    CallResponse.CallResponseStart(builder)
    CallResponse.CallResponseAddRequestId(builder, call.request_id)
    CallResponse.CallResponseAddPayloadType(builder, ResponsePayload.ResponsePayload.{{.ResponseTable}})
    CallResponse.CallResponseAddPayload(builder, payload)
    response = CallResponse.CallResponseEnd(builder)
    builder.Finish(response)
    return bytes(builder.Output())


{{end}}`

const pyContractTmpl = `# Code generated by pluginart. DO NOT EDIT.
CONTRACT_HASH = '{{.ContractHash}}'
`

const pyHandlerTmpl = `# Edit this file to implement your plugin logic.

def handle(payload: bytes) -> bytes:
    """Use Decode<Method>Request and Build<Method>CallResponse helpers."""
    raise NotImplementedError
`

const pyRequirementsTmpl = `pluginart==0.2.0
flatbuffers>=24.3.25
`

const pyDockerfileTmpl = `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENTRYPOINT ["python", "plugin.py"]
`
