package cmd

const pyClientTmpl = `# Code generated by pluginart. DO NOT EDIT.
import os
import socket
import struct
import sys

import flatbuffers
import flatbuffers.encode
import flatbuffers.packer
import flatbuffers.table

# ── Wire protocol ─────────────────────────────────────────────────────────────

_MAGIC = b'PLGN'
_HDR_SIZE = 9  # 4 magic + 4 length + 1 flags

MSG_HANDSHAKE_REQUEST  = 0x01
MSG_HANDSHAKE_RESPONSE = 0x02
MSG_CALL_REQUEST       = 0x03
MSG_CALL_RESPONSE      = 0x04
MSG_PLUGIN_ERROR       = 0x05
MSG_CANCEL             = 0x06
MSG_PING               = 0x07
MSG_PONG               = 0x08

CONTRACT_HASH = "{{.ContractHash}}"


def _send_frame(sock: socket.socket, flags: int, payload: bytes) -> None:
    hdr = _MAGIC + struct.pack('<IB', len(payload), flags)
    sock.sendall(hdr + payload)


def _recv_frame(sock: socket.socket) -> tuple[int, bytes]:
    hdr = b''
    while len(hdr) < _HDR_SIZE:
        chunk = sock.recv(_HDR_SIZE - len(hdr))
        if not chunk:
            raise ConnectionError('connection closed')
        hdr += chunk
    if hdr[:4] != _MAGIC:
        raise ValueError(f'bad magic: {hdr[:4]!r}')
    length, flags = struct.unpack('<IB', hdr[4:])
    payload = b''
    while len(payload) < length:
        chunk = sock.recv(length - len(payload))
        if not chunk:
            raise ConnectionError('connection closed mid-payload')
        payload += chunk
    return flags, payload


def _build_handshake_request(contract_hash: str, plugin_name: str) -> bytes:
    b = flatbuffers.Builder(128)
    ch = b.CreateString(contract_hash)
    pn = b.CreateString(plugin_name)
    b.StartObject(3)
    b.PrependUOffsetTRelativeSlot(0, ch, 0)
    b.PrependUOffsetTRelativeSlot(1, pn, 0)
    b.PrependUint16Slot(2, 1, 0)
    root = b.EndObject()
    b.Finish(root)
    return bytes(b.Output())


def _parse_handshake_response(buf: bytes) -> tuple[bool, str]:
    ba = bytearray(buf)
    root_pos = flatbuffers.encode.Get(flatbuffers.packer.uoffset, ba, 0) + 0
    tab = flatbuffers.table.Table(ba, root_pos)
    # field 0 (slot 4): ok bool
    o = tab.Offset(4)
    ok = bool(ba[tab.Pos + o]) if o else False
    # field 1 (slot 6): error string
    o = tab.Offset(6)
    error = tab.String(o + tab.Pos).decode('utf-8') if o else ''
    return ok, error


# ── Client ────────────────────────────────────────────────────────────────────

class {{.Namespace}}Client:
    """Typed host-side client for the {{.Namespace}} plugin."""

    def __init__(self, sock_path: str | None = None, addr: tuple[str, int] | None = None) -> None:
        if sock_path:
            self._sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
            self._sock.connect(sock_path)
        elif addr:
            self._sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            self._sock.connect(addr)
        else:
            raise ValueError('provide sock_path or addr')
        self._handshake()

    def _handshake(self) -> None:
        req_bytes = _build_handshake_request(CONTRACT_HASH, '{{.Namespace}}')
        _send_frame(self._sock, MSG_HANDSHAKE_REQUEST, req_bytes)
        flags, payload = _recv_frame(self._sock)
        if flags != MSG_HANDSHAKE_RESPONSE:
            raise RuntimeError(f'unexpected frame type during handshake: {flags:#x}')
        ok, err = _parse_handshake_response(payload)
        if not ok:
            raise RuntimeError(f'handshake rejected: {err}')

    def _call(self, payload: bytes) -> bytes:
        _send_frame(self._sock, MSG_CALL_REQUEST, payload)
        flags, resp = _recv_frame(self._sock)
        if flags == MSG_PLUGIN_ERROR:
            raise RuntimeError(f'plugin error: {resp!r}')
        if flags != MSG_CALL_RESPONSE:
            raise RuntimeError(f'unexpected frame type: {flags:#x}')
        return resp

    def close(self) -> None:
        self._sock.close()

    def __enter__(self) -> '{{.Namespace}}Client':
        return self

    def __exit__(self, *_: object) -> None:
        self.close()
{{range .Methods}}
    def {{.Name}}(self, request_bytes: bytes) -> bytes:
        """Call {{.Name}} on the plugin. request_bytes is a raw FlatBuffers {{.RequestTable}}."""
        return self._call(request_bytes)
{{end}}`

const pyPluginTmpl = `# Code generated by pluginart. DO NOT EDIT.
import os
import socket
import struct
import sys
import threading

import flatbuffers
import flatbuffers.encode
import flatbuffers.packer
import flatbuffers.table

from handler import handle

# ── Wire protocol ─────────────────────────────────────────────────────────────

_MAGIC = b'PLGN'
_HDR_SIZE = 9

MSG_HANDSHAKE_REQUEST  = 0x01
MSG_HANDSHAKE_RESPONSE = 0x02
MSG_CALL_REQUEST       = 0x03
MSG_CALL_RESPONSE      = 0x04
MSG_PLUGIN_ERROR       = 0x05
MSG_CANCEL             = 0x06
MSG_PING               = 0x07
MSG_PONG               = 0x08

CONTRACT_HASH = "{{.ContractHash}}"


def _send_frame(sock: socket.socket, flags: int, payload: bytes) -> None:
    hdr = _MAGIC + struct.pack('<IB', len(payload), flags)
    sock.sendall(hdr + payload)


def _recv_frame(sock: socket.socket) -> tuple[int, bytes]:
    hdr = b''
    while len(hdr) < _HDR_SIZE:
        chunk = sock.recv(_HDR_SIZE - len(hdr))
        if not chunk:
            raise ConnectionError('connection closed')
        hdr += chunk
    if hdr[:4] != _MAGIC:
        raise ValueError(f'bad magic: {hdr[:4]!r}')
    length, flags = struct.unpack('<IB', hdr[4:])
    payload = b''
    while len(payload) < length:
        chunk = sock.recv(length - len(payload))
        if not chunk:
            raise ConnectionError('connection closed mid-payload')
        payload += chunk
    return flags, payload


def _parse_handshake_request(buf: bytes) -> tuple[str, str]:
    ba = bytearray(buf)
    root_pos = flatbuffers.encode.Get(flatbuffers.packer.uoffset, ba, 0) + 0
    tab = flatbuffers.table.Table(ba, root_pos)
    # field 0 (slot 4): contract_hash string
    o = tab.Offset(4)
    contract_hash = tab.String(o + tab.Pos).decode('utf-8') if o else ''
    # field 1 (slot 6): plugin_name string
    o = tab.Offset(6)
    plugin_name = tab.String(o + tab.Pos).decode('utf-8') if o else ''
    return contract_hash, plugin_name


def _build_handshake_response(ok: bool, error: str = '') -> bytes:
    b = flatbuffers.Builder(64)
    err_off = b.CreateString(error) if error else 0
    b.StartObject(2)
    b.PrependBoolSlot(0, ok, False)
    if err_off:
        b.PrependUOffsetTRelativeSlot(1, err_off, 0)
    root = b.EndObject()
    b.Finish(root)
    return bytes(b.Output())


def _build_pong(seq: int) -> bytes:
    b = flatbuffers.Builder(16)
    b.StartObject(1)
    b.PrependUint64Slot = getattr(b, 'PrependUint64Slot', None)
    # manually encode uint64 in slot 0 (vtable offset 4)
    b.Slot(0)
    b.PrependUint64(seq)
    root = b.EndObject()
    b.Finish(root)
    return bytes(b.Output())


# ── Connection handler ────────────────────────────────────────────────────────

def _handle_conn(conn: socket.socket) -> None:
    try:
        # handshake
        flags, payload = _recv_frame(conn)
        if flags != MSG_HANDSHAKE_REQUEST:
            return
        contract_hash, _ = _parse_handshake_request(payload)
        if contract_hash != CONTRACT_HASH:
            resp = _build_handshake_response(False, f'contract mismatch: got {contract_hash}')
            _send_frame(conn, MSG_HANDSHAKE_RESPONSE, resp)
            return
        _send_frame(conn, MSG_HANDSHAKE_RESPONSE, _build_handshake_response(True))

        # serve
        while True:
            flags, payload = _recv_frame(conn)
            if flags == MSG_CALL_REQUEST:
                try:
                    resp = handle(payload)
                    _send_frame(conn, MSG_CALL_RESPONSE, resp)
                except Exception as exc:
                    err_bytes = str(exc).encode()
                    _send_frame(conn, MSG_PLUGIN_ERROR, err_bytes)
            elif flags == MSG_PING:
                _send_frame(conn, MSG_PONG, payload)
            elif flags == MSG_CANCEL:
                pass  # best-effort; ignore
            else:
                break
    except (ConnectionError, OSError):
        pass
    finally:
        conn.close()


# ── Main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    sock_path = os.environ.get('PLUGIN_SOCKET', '')
    addr_str  = os.environ.get('PLUGIN_ADDR', '')

    if sock_path:
        srv = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        srv.bind(sock_path)
    elif addr_str:
        host, port = addr_str.rsplit(':', 1)
        srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        srv.bind((host, int(port)))
    else:
        print('PLUGIN_SOCKET or PLUGIN_ADDR must be set', file=sys.stderr)
        sys.exit(1)

    srv.listen(128)
    print('READY', flush=True)

    while True:
        conn, _ = srv.accept()
        t = threading.Thread(target=_handle_conn, args=(conn,), daemon=True)
        t.start()


if __name__ == '__main__':
    main()
`

const pyHandlerTmpl = `# Edit this file to implement your plugin logic.

def handle(payload: bytes) -> bytes:
    """payload is a raw FlatBuffers CallRequest. Return raw FlatBuffers CallResponse bytes."""
    raise NotImplementedError
`

const pyRequirementsTmpl = `flatbuffers>=24.3.25
`

const pyDockerfileTmpl = `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENTRYPOINT ["python", "plugin.py"]
`
