package cmd

const schemaTmpl = `// {{.Name}}.fbs
// Edit this file to define your plugin's methods.
// Run: pluginart gen client --schema ./schema/{{.Name}}.fbs
//      pluginart gen plugin --lang go --schema ./schema/{{.Name}}.fbs

namespace {{.Name}};

// ── Step 1: Define one table per method input ─────────────────────────────

table ExampleRequest {
  input: string;
  // Add your fields here
}

// ── Step 2: Define one table per method output ────────────────────────────

table ExampleResponse {
  output: string;
  // Add your fields here
}

// ── Step 3: Register methods in these unions ──────────────────────────────
// Add new methods by adding new table pairs above and listing them here.

union RequestPayload  { ExampleRequest }
union ResponsePayload { ExampleResponse }

// ── Do not edit below this line ───────────────────────────────────────────

table CallRequest {
  request_id:       uint64;
  deadline_unix_ms: int64;
  trace_id:         string;
  span_id:          string;
  payload:          RequestPayload;
}

table CallResponse {
  request_id: uint64;
  payload:    ResponsePayload;
}

table ShmHandle { offset: uint64; length: uint64; }

table PluginError {
  code:    uint16;
  message: string;
  retry:   bool;
}

root_type CallRequest;
`

const clientTmpl = `// Code generated by pluginart. DO NOT EDIT.
package {{.Namespace}}

import (
	"context"

	"github.com/dlahoza/pluginart/pkg/runtime"
)

// Client is the typed host-side client for the {{.Namespace}} plugin.
type Client struct {
	manager *runtime.PluginManager
	name    string
}

// NewClient creates a Client that calls pluginName via manager.
func NewClient(manager *runtime.PluginManager, pluginName string) *Client {
	return &Client{manager: manager, name: pluginName}
}
{{range .Methods}}
// {{.Name}} calls the {{.Name}} method on the plugin.
func (c *Client) {{.Name}}(ctx context.Context, req *{{.RequestTable}}) (*{{.ResponseTable}}, error) {
	payload := build{{.Name}}Request(req)
	raw, err := c.manager.Call(ctx, c.name, payload)
	if err != nil {
		return nil, err
	}
	return parse{{.Name}}Response(raw)
}
{{end}}`

const contractTmpl = `// Code generated by pluginart. DO NOT EDIT.
package {{.Package}}

// ContractHash is the SHA-256 of the schema file used to generate this code.
// The pluginart runtime verifies this matches on every connection.
const ContractHash = "{{.Hash}}"
`

const pluginMainTmpl = `// Code generated by pluginart. DO NOT EDIT.
package main

import (
	"fmt"
	"net"
	"os"

	"github.com/dlahoza/pluginart/pkg/protocol"
)

func main() {
	var (
		ln  net.Listener
		err error
	)
	switch {
	case os.Getenv("PLUGIN_SOCKET") != "":
		ln, err = net.Listen("unix", os.Getenv("PLUGIN_SOCKET"))
	case os.Getenv("PLUGIN_ADDR") != "":
		ln, err = net.Listen("tcp", os.Getenv("PLUGIN_ADDR"))
	default:
		fmt.Fprintln(os.Stderr, "PLUGIN_SOCKET or PLUGIN_ADDR must be set")
		os.Exit(1)
	}
	if err != nil {
		fmt.Fprintf(os.Stderr, "listen: %v\n", err)
		os.Exit(1)
	}

	fmt.Println("READY")

	handler := &PluginHandler{}
	server := protocol.NewServer(ln, handler, ContractHash)
	if err := server.Serve(); err != nil {
		fmt.Fprintf(os.Stderr, "serve: %v\n", err)
		os.Exit(1)
	}
}
`

const pluginHandlerTmpl = `package main

import (
	"context"
	"fmt"
)

// PluginHandler implements the plugin logic. Edit this file.
type PluginHandler struct{}

// Handle is called for every incoming request. payload is a raw FlatBuffers CallRequest.
// Return the raw FlatBuffers CallResponse bytes.
func (h *PluginHandler) Handle(ctx context.Context, payload []byte) ([]byte, error) {
	// TODO: decode payload and return response
	return nil, fmt.Errorf("not implemented")
}
`

const pluginGomodTmpl = `module {{.Name}}-plugin

go 1.23

require (
	github.com/dlahoza/pluginart v0.1.0
	github.com/google/flatbuffers v25.12.19+incompatible
)
`

const pluginDockerfileTmpl = `FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o plugin .

FROM alpine:3.20
RUN adduser -D -u 1000 plugin
USER plugin
COPY --from=builder /app/plugin /plugin
ENTRYPOINT ["/plugin"]
`
