package cmd

const tsPluginTmpl = `// Code generated by pluginart. DO NOT EDIT.
import { serve } from 'pluginart';
import { CONTRACT_HASH } from './contract';
import { handle } from './handler';

serve(handle, { contractHash: CONTRACT_HASH });
`

const tsClientTmpl = `// Code generated by pluginart. DO NOT EDIT.
import { PluginManager } from 'pluginart';

export class {{.Namespace}}Client {
  constructor(private manager: PluginManager, private pluginName: string) {}
{{range .Methods}}
  /** Call {{.Name}} on the plugin. payload is a full schema CallRequest FlatBuffer. */
  async {{.Name}}(payload: Buffer): Promise<Buffer> {
    return this.manager.call(this.pluginName, payload);
  }
{{end}}}
`

const tsContractTmpl = `// Code generated by pluginart. DO NOT EDIT.
export const CONTRACT_HASH = '{{.ContractHash}}';
`

const tsHandlerTmpl = `// Edit this file to implement your plugin logic.

export function handle(payload: Buffer): Buffer {
  // payload is a raw FlatBuffers CallRequest.
  // Return raw FlatBuffers CallResponse bytes.
  throw new Error('not implemented');
}
`

const tsPackageJSONTmpl = `{
  "name": "{{.Name}}-plugin",
  "version": "0.1.0",
  "main": "dist/plugin.js",
  "scripts": {
    "build": "tsc",
    "start": "node dist/plugin.js"
  },
  "dependencies": {
    "pluginart": "0.2.0",
    "flatbuffers": "^25.2.10"
  },
  "devDependencies": {
    "typescript": "^5.0.0",
    "@types/node": "^22.0.0"
  }
}
`

const tsTsconfigTmpl = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "commonjs",
    "outDir": "dist",
    "strict": true,
    "esModuleInterop": true
  },
  "include": ["*.ts"]
}
`

const tsDockerfileTmpl = `FROM node:22-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
ENTRYPOINT ["node", "dist/plugin.js"]
`
