package cmd

const pyPluginTmpl = `# Code generated by pluginart. DO NOT EDIT.
from pluginart import serve
from contract import CONTRACT_HASH
from handler import handle

if __name__ == '__main__':
    serve(handle, contract_hash=CONTRACT_HASH)
`

const pyClientTmpl = `# Code generated by pluginart. DO NOT EDIT.
from pluginart import PluginManager


class {{.Namespace}}Client:
    """Typed host-side client for the {{.Namespace}} plugin."""

    def __init__(self, manager: PluginManager, plugin_name: str) -> None:
        self._manager = manager
        self._plugin_name = plugin_name
{{range .Methods}}
    def {{.Name}}(self, payload: bytes) -> bytes:
        """Call {{.Name}} on the plugin. payload is a full schema CallRequest FlatBuffer."""
        return self._manager.call(self._plugin_name, payload)
{{end}}`

const pyContractTmpl = `# Code generated by pluginart. DO NOT EDIT.
CONTRACT_HASH = '{{.ContractHash}}'
`

const pyHandlerTmpl = `# Edit this file to implement your plugin logic.

def handle(payload: bytes) -> bytes:
    """payload is a raw FlatBuffers CallRequest. Return raw FlatBuffers CallResponse bytes."""
    raise NotImplementedError
`

const pyRequirementsTmpl = `pluginart==0.2.0
flatbuffers>=24.3.25
`

const pyDockerfileTmpl = `FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENTRYPOINT ["python", "plugin.py"]
`
