// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class RepeatRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RepeatRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRepeatRequest(bb:flatbuffers.ByteBuffer, obj?:RepeatRequest):RepeatRequest {
  return (obj || new RepeatRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRepeatRequest(bb:flatbuffers.ByteBuffer, obj?:RepeatRequest):RepeatRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RepeatRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

input():string|null
input(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
input(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

count():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startRepeatRequest(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addInput(builder:flatbuffers.Builder, inputOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, inputOffset, 0);
}

static addCount(builder:flatbuffers.Builder, count:number) {
  builder.addFieldInt32(1, count, 0);
}

static endRepeatRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createRepeatRequest(builder:flatbuffers.Builder, inputOffset:flatbuffers.Offset, count:number):flatbuffers.Offset {
  RepeatRequest.startRepeatRequest(builder);
  RepeatRequest.addInput(builder, inputOffset);
  RepeatRequest.addCount(builder, count);
  return RepeatRequest.endRepeatRequest(builder);
}
}
