// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { RepeatRequest } from '../repeat/repeat-request.js';


export enum RequestPayload {
  NONE = 0,
  RepeatRequest = 1
}

export function unionToRequestPayload(
  type: RequestPayload,
  accessor: (obj:RepeatRequest) => RepeatRequest|null
): RepeatRequest|null {
  switch(RequestPayload[type]) {
    case 'NONE': return null; 
    case 'RepeatRequest': return accessor(new RepeatRequest())! as RepeatRequest;
    default: return null;
  }
}

export function unionListToRequestPayload(
  type: RequestPayload, 
  accessor: (index: number, obj:RepeatRequest) => RepeatRequest|null, 
  index: number
): RepeatRequest|null {
  switch(RequestPayload[type]) {
    case 'NONE': return null; 
    case 'RepeatRequest': return accessor(index, new RepeatRequest())! as RepeatRequest;
    default: return null;
  }
}
