// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { RepeatResponse } from '../repeat/repeat-response.js';


export enum ResponsePayload {
  NONE = 0,
  RepeatResponse = 1
}

export function unionToResponsePayload(
  type: ResponsePayload,
  accessor: (obj:RepeatResponse) => RepeatResponse|null
): RepeatResponse|null {
  switch(ResponsePayload[type]) {
    case 'NONE': return null; 
    case 'RepeatResponse': return accessor(new RepeatResponse())! as RepeatResponse;
    default: return null;
  }
}

export function unionListToResponsePayload(
  type: ResponsePayload, 
  accessor: (index: number, obj:RepeatResponse) => RepeatResponse|null, 
  index: number
): RepeatResponse|null {
  switch(ResponsePayload[type]) {
    case 'NONE': return null; 
    case 'RepeatResponse': return accessor(index, new RepeatResponse())! as RepeatResponse;
    default: return null;
  }
}
