# automatically generated by the FlatBuffers compiler, do not modify

# namespace: repeat

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RepeatResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RepeatResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRepeatResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RepeatResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RepeatResponse
    def Output(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def RepeatResponseStart(builder):
    builder.StartObject(1)

def Start(builder):
    RepeatResponseStart(builder)

def RepeatResponseAddOutput(builder, output):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(output), 0)

def AddOutput(builder, output):
    RepeatResponseAddOutput(builder, output)

def RepeatResponseEnd(builder):
    return builder.EndObject()

def End(builder):
    return RepeatResponseEnd(builder)
