// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package echo

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CallResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsCallResponse(buf []byte, offset flatbuffers.UOffsetT) *CallResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CallResponse{}
	x.Init(buf, n+offset)
	return x
}

func FinishCallResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCallResponse(buf []byte, offset flatbuffers.UOffsetT) *CallResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CallResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCallResponseBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CallResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CallResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CallResponse) RequestId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CallResponse) MutateRequestId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func (rcv *CallResponse) PayloadType() ResponsePayload {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ResponsePayload(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *CallResponse) MutatePayloadType(n ResponsePayload) bool {
	return rcv._tab.MutateByteSlot(6, byte(n))
}

func (rcv *CallResponse) Payload(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func CallResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func CallResponseAddRequestId(builder *flatbuffers.Builder, requestId uint64) {
	builder.PrependUint64Slot(0, requestId, 0)
}
func CallResponseAddPayloadType(builder *flatbuffers.Builder, payloadType ResponsePayload) {
	builder.PrependByteSlot(1, byte(payloadType), 0)
}
func CallResponseAddPayload(builder *flatbuffers.Builder, payload flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(payload), 0)
}
func CallResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
