// Code generated by pluginart. DO NOT EDIT.
package echo

import (
	"context"

	"github.com/dlahoza/pluginart/pkg/runtime"
	flatbuffers "github.com/google/flatbuffers/go"
)

// Client is the typed host-side client for the echo plugin.
type Client struct {
	manager *runtime.PluginManager
	name    string
}

// NewClient creates a Client that calls pluginName via manager.
func NewClient(manager *runtime.PluginManager, pluginName string) *Client {
	return &Client{manager: manager, name: pluginName}
}

// Echo calls the Echo method on the plugin.
func (c *Client) Echo(ctx context.Context, builder *flatbuffers.Builder, req flatbuffers.UOffsetT) (*EchoResponse, error) {
	payload := BuildEchoCallRequest(builder, req)
	raw, err := c.manager.Call(ctx, c.name, payload)
	if err != nil {
		return nil, err
	}
	resp, _, err := DecodeEchoResponse(raw)
	return resp, err
}
