// Code generated by pluginart. DO NOT EDIT.
import * as flatbuffers from 'flatbuffers';
import { CallRequest } from './repeat/call-request';
import { CallResponse } from './repeat/call-response';
import { RepeatRequest } from './repeat/repeat-request';
import { RepeatResponse } from './repeat/repeat-response';
import { RequestPayload } from './repeat/request-payload';
import { ResponsePayload } from './repeat/response-payload';

export interface CallContext {
  requestId: bigint;
}

export function BuildRepeatCallRequest(builder: flatbuffers.Builder, payload: flatbuffers.Offset): Buffer {
  CallRequest.startCallRequest(builder);
  CallRequest.addPayloadType(builder, RequestPayload.RepeatRequest);
  CallRequest.addPayload(builder, payload);
  const request = CallRequest.endCallRequest(builder);
  CallRequest.finishCallRequestBuffer(builder, request);
  return Buffer.from(builder.asUint8Array());
}

export function DecodeRepeatRequest(payload: Buffer): { payload: RepeatRequest; call: CallContext } {
  const request = CallRequest.getRootAsCallRequest(new flatbuffers.ByteBuffer(new Uint8Array(payload)));
  const got = request.payloadType();
  if (got !== RequestPayload.RepeatRequest) {
    throw new Error(`expected RepeatRequest payload, got ${got}`);
  }
  const out = request.payload(new RepeatRequest()) as RepeatRequest | null;
  if (!out) throw new Error('missing RepeatRequest payload');
  return { payload: out, call: { requestId: request.requestId() } };
}

export function BuildRepeatCallResponse(call: CallContext, builder: flatbuffers.Builder, payload: flatbuffers.Offset): Buffer {
  CallResponse.startCallResponse(builder);
  CallResponse.addRequestId(builder, call.requestId);
  CallResponse.addPayloadType(builder, ResponsePayload.RepeatResponse);
  CallResponse.addPayload(builder, payload);
  const response = CallResponse.endCallResponse(builder);
  builder.finish(response);
  return Buffer.from(builder.asUint8Array());
}

export function DecodeRepeatResponse(payload: Buffer): { payload: RepeatResponse; call: CallContext } {
  const response = CallResponse.getRootAsCallResponse(new flatbuffers.ByteBuffer(new Uint8Array(payload)));
  const got = response.payloadType();
  if (got !== ResponsePayload.RepeatResponse) {
    throw new Error(`expected RepeatResponse payload, got ${got}`);
  }
  const out = response.payload(new RepeatResponse()) as RepeatResponse | null;
  if (!out) throw new Error('missing RepeatResponse payload');
  return { payload: out, call: { requestId: response.requestId() } };
}

