// Code generated by pluginart. DO NOT EDIT.
import * as flatbuffers from 'flatbuffers';
import { PluginManager } from 'pluginart';
import { RepeatResponse } from './repeat/repeat-response';

import { BuildRepeatCallRequest, DecodeRepeatResponse } from './pluginart_helpers';

export class repeatClient {
  constructor(private manager: PluginManager, private pluginName: string) {}

  /** Call Repeat on the plugin. payload is a RepeatRequest table offset. */
  async Repeat(builder: flatbuffers.Builder, payload: flatbuffers.Offset): Promise<RepeatResponse> {
    const raw = await this.manager.call(this.pluginName, BuildRepeatCallRequest(builder, payload));
    return DecodeRepeatResponse(raw).payload;
  }
}
