// Code generated by pluginart. DO NOT EDIT.
import * as flatbuffers from 'flatbuffers';
import { CallRequest } from './echo/call-request';
import { CallResponse } from './echo/call-response';
import { EchoRequest } from './echo/echo-request';
import { EchoResponse } from './echo/echo-response';
import { RequestPayload } from './echo/request-payload';
import { ResponsePayload } from './echo/response-payload';

export interface CallContext {
  requestId: bigint;
}

export function BuildEchoCallRequest(builder: flatbuffers.Builder, payload: flatbuffers.Offset): Buffer {
  CallRequest.startCallRequest(builder);
  CallRequest.addPayloadType(builder, RequestPayload.EchoRequest);
  CallRequest.addPayload(builder, payload);
  const request = CallRequest.endCallRequest(builder);
  CallRequest.finishCallRequestBuffer(builder, request);
  return Buffer.from(builder.asUint8Array());
}

export function DecodeEchoRequest(payload: Buffer): { payload: EchoRequest; call: CallContext } {
  const request = CallRequest.getRootAsCallRequest(new flatbuffers.ByteBuffer(new Uint8Array(payload)));
  const got = request.payloadType();
  if (got !== RequestPayload.EchoRequest) {
    throw new Error(`expected EchoRequest payload, got ${got}`);
  }
  const out = request.payload(new EchoRequest()) as EchoRequest | null;
  if (!out) throw new Error('missing EchoRequest payload');
  return { payload: out, call: { requestId: request.requestId() } };
}

export function BuildEchoCallResponse(call: CallContext, builder: flatbuffers.Builder, payload: flatbuffers.Offset): Buffer {
  CallResponse.startCallResponse(builder);
  CallResponse.addRequestId(builder, call.requestId);
  CallResponse.addPayloadType(builder, ResponsePayload.EchoResponse);
  CallResponse.addPayload(builder, payload);
  const response = CallResponse.endCallResponse(builder);
  builder.finish(response);
  return Buffer.from(builder.asUint8Array());
}

export function DecodeEchoResponse(payload: Buffer): { payload: EchoResponse; call: CallContext } {
  const response = CallResponse.getRootAsCallResponse(new flatbuffers.ByteBuffer(new Uint8Array(payload)));
  const got = response.payloadType();
  if (got !== ResponsePayload.EchoResponse) {
    throw new Error(`expected EchoResponse payload, got ${got}`);
  }
  const out = response.payload(new EchoResponse()) as EchoResponse | null;
  if (!out) throw new Error('missing EchoResponse payload');
  return { payload: out, call: { requestId: response.requestId() } };
}

